(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,750,300);


(lib.dacyuk = function() {
	this.initialize(img.dacyuk);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,226,257);


(lib.headphone = function() {
	this.initialize(img.headphone);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,726,270);


(lib.iphone = function() {
	this.initialize(img.iphone);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,107,161);


(lib.kaprizov = function() {
	this.initialize(img.kaprizov);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,218,270);


(lib.kokorin = function() {
	this.initialize(img.kokorin);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,305,300);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,255,87);


(lib.samedov = function() {
	this.initialize(img.samedov);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,315,371);


(lib.samsung = function() {
	this.initialize(img.samsung);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,105,175);


(lib.seif = function() {
	this.initialize(img.seif);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,261,342);


(lib.shved = function() {
	this.initialize(img.shved);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,317,324);


(lib.slayd1 = function() {
	this.initialize(img.slayd1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,263,151);


(lib.slayd2 = function() {
	this.initialize(img.slayd2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,263,151);


(lib.slayd3 = function() {
	this.initialize(img.slayd3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,263,151);


(lib.smolov = function() {
	this.initialize(img.smolov);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,264,214);


(lib.tv = function() {
	this.initialize(img.tv);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,274,186);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Символ55 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D5291C").s().p("AujDGQgRgDgQgGQgPgGgNgIQgNgIgLgLQgKgLgJgNQgJgNgFgOQgHgPgCgRQgEgRAAgSQAAgRADgQQADgPAFgPQAFgPAIgMQAIgOAKgLQALgLANgIQANgJAPgGQAQgHARgDQASgDAUAAQAVAAAkAJQAYAJAPAPIgfA2QgQgKgMgEQgQgGgVAAQgSAAgQAGQgQAHgMAMQgMAMgHASQgHARAAAXQAAAUAHASQAHASANAMQAMANARAHQASAHAVAAQASAAARgFQASgGAQgMIAbA2QgHAIgLAHQgLAGgNAFQgnALgVAAQgSAAgRgDgA0lDCIAAk4QA1gDArAAQAcAAAUAHQAUAFANALQANALAGAOQAGAOgBARQAAAYgJARQgIAQgTAMIAAABQAKADAHAGQAIAGAHAJQAGAJAEAMQAEAMgBAPQAAAYgJATQgIASgQAMQgRAMgWAGQgVAGgaAAQg/AAgcgDgAzdB/QALADAOAAQAVAAAKgJQAKgJAAgQQAAgOgKgHQgKgHgSAAIgcAAgAzdgzIAAA4IAZAAQAOAAAJgGQAJgIAAgQQAAgNgKgIQgKgHgOAAgARmDDIAAk6IC6AAIAABEIhyAAIAAA2IBmAAIAABEIhmAAIAAA5IB4AAIAABDgAOSDDIAAj2IheAAIAAhEIEFAAIAABEIhfAAIAAD2gAK/DDIAAjDIiMDDIg+AAIAAk6IBIAAIAADDICLjDIA/AAIAAE6gAF/DDIgahCIh9AAIgaBCIhIAAICDk6IBAAAICEE6gAFKA+IgjhZIgkBZIBHAAgAAWDDIAAj2IhtAAIAAD2IhIAAIAAk6ID9AAIAAE6gAmtC/QgOgEgHgGIAZg9QAMAIALAAQAIAAAGgDQAGgDADgHIAEgJIiHjhIBRAAIBYCZIBBiZIBIAAIhqDwQgIASgJAOQgKAOgKAJQgMAKgNAEQgOAFgQAAQgNAAgOgEgAquDDIAAj2IheAAIAAhEIEFAAIAABEIhfAAIAAD2gAJdiFQgSgFgMgKQgMgJgHgNQgGgOAAgQIBEAAQAAANAGAFQAHAFAOAAQAOAAAGgEQAGgFAAgOIBEAAQAAAQgGAOQgHANgMAKQgNAJgRAFQgRAFgWAAQgWAAgSgFg");
	this.shape.setTransform(131.8,20.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ55, new cjs.Rectangle(0,0,263.5,40.2), null);


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("APMA/IgKgDQgFgDgDgEQgCgEAAgGQAAgEABgDQABgDADgDQADgCAEgCIAJgDIgBgDIABgEIgHgDIgFgFIgDgHIgBgFQAAgFACgEQACgFADgDQAEgEAFgBQAFgCAHAAIAIABIAIADIATgEIABARIgJABIAAAGQAAAEgBADQgCAFgDADQgEADgEACQgFACgGAAIAAACIABACIALACIAKAEQAEACADAEQADAEgBAFQABAGgDAEQgDAEgFACIgKAEIgNABIgNgBgAPOAoQAAAAgBABQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAAAABABQABAAAAAAQAFACAGAAIALgBQAAgBABAAQABAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAgBAAQgBgBAAAAIgLgBIgLABgAPTgJQgCACgBADQABADACABQACACAEAAQADAAACgCQADgBAAgDQAAgDgCgCQgCgDgEAAQgEAAgCADgAkCA/IAAhaIAVAAIAAAFQADgDAEgCQAFgBAFAAQAHAAAGACQAEACAEAFQAEAEACAGQACAGAAAGQAAAHgDAGQgCAGgEAFQgFAFgGACQgHADgHAAQgHAAgFgCIAAAcgAjogHIgFAEIAAASQAEACAGAAIAGgBIAEgDQADgEAAgGQAAgEgDgEQgDgEgGAAQgDAAgDACgAUGAjQgHgDgEgEQgEgFgDgGQgCgGAAgHQAAgGACgGQADgGAEgFQAEgEAHgDQAGgCAIAAQAGAAAGACQAFACAEAEQAFAEACAFQACAGABAFQgBAHgBAEIgqAAQACAEAEACQADACAGAAQAIAAAIgEIAGAPQgEADgHACQgGACgHAAQgIAAgGgCgAUdgCQAAgEgCgCQgDgDgFAAQgFAAgDACQgDACgBAFIAWAAIAAAAgAS/AjQgHgDgEgEQgFgFgCgGQgDgGAAgHQAAgGADgGQACgGAFgFQAEgEAHgDQAGgCAHAAQAHAAAFACQAFACAFAEQAEAEADAFQACAGAAAFQAAAHgBAEIgqAAQABAEAFACQADACAGAAQAHAAAJgEIAGAPQgFADgGACQgHACgHAAQgIAAgFgCgATWgCQAAgEgDgCQgCgDgGAAQgEAAgEACQgCACgCAFIAXAAIAAAAgAJbAkIgJgDQgFgBgFgDIgHgGIgGgHIgEgJIgDgJIgBgLIABgKIADgKIADgIIAGgIIAIgGQAEgDAEgBIAKgDIALgBQAHAAALACQAIADAGAFIgJASQgDgDgGgCQgGgCgGAAQgFAAgGABQgFACgEAEQgEAEgCAFQgCAGAAAHQAAAHACAGQACAEAEAEQADAEAGACQAFACAHAAIAJgCIAGgDIAAgLIgUAAIAAgUIApAAIAAArIgHAGIgKAEIgKADIgKABIgMgBgAEzAkIgIgDQgIgEgDgEIAKgNQADACAHADQAGACAFAAQAEAAABgCQAAgCgGgCIgLgDQgIgCgDgEIgFgEQgBgEAAgEQAAgFACgEQACgEAEgCIAIgEIAJgBQAHAAAKACQAGADAEADIgJAPQgKgGgHAAQgFAAAAADQAAACAFABIAMADQAHACAFADIADAFQACAEgBAEQAAAEgBAEQgCAEgEADIgJAEQgEACgHAAIgKgBgADzAkIgIgDQgIgEgCgEIAJgNQADACAHADQAGACAFAAQAEAAABgCQAAgCgGgCIgLgDQgHgCgEgEIgFgEQgBgEAAgEQAAgFACgEQACgEAEgCIAIgEIAJgBQAHAAAKACQAFADAFADIgIAPQgLgGgHAAQgFAAAAADQAAACAGABIALADQAHACAFADIADAFQACAEgBAEQAAAEgBAEQgCAEgEADIgJAEQgEACgHAAIgKgBgACmAjQgDgBgDgDQgEgDgCgFQgBgFAAgGIAAgnIAVAAIAAAiQAAAFABACQADADAEAAIAFgBQACgBADgDIAAgnIAVAAIAAA+IgVAAIAAgGQgCADgEACQgGADgGAAIgIgCgAhjAiQgHgCgEgFQgFgEgCgGQgDgGAAgHQAAgGADgGQACgGAFgFQAEgEAHgDQAGgCAIAAQAIAAAGACQAHADAFAEQAEAFADAGQACAGAAAGQAAAHgCAGQgDAGgEAEQgFAFgHACQgGADgIAAQgIAAgGgDgAhegFIgDAEIgBAFQABAGADAEQAEADAFAAQAFAAAEgDIADgFIABgFQAAgFgEgEQgEgEgFAAQgFAAgEAEgAk5AjQgGgDgEgEQgFgFgDgGQgCgGAAgHQAAgGACgGQADgGAFgFQAEgEAGgDQAHgCAIAAQAFAAAGACQAGACADAEQAFAEADAFQACAGAAAFQAAAHgBAEIgqAAQACAEAEACQADACAGAAQAHAAAJgEIAGAPQgFADgHACQgFACgHAAQgIAAgHgCgAkhgCQAAgEgDgCQgDgDgEAAQgGAAgCACQgEACgBAFIAXAAIAAAAgAnJAjQgGgDgFgEQgEgFgDgGQgDgGABgHQgBgGADgGQADgGAEgFQAFgEAFgDQAGgCAIAAQAIAAAHACQAHACAEAFIgKAQQgDgDgDgCIgHgBQgGAAgDAEIgEAEIgBAFQAAADABACIAEAFQAEADAFAAQAFAAADgCIAGgFIAKAQIgFAFIgGADQgKADgEAAQgJAAgGgCgApbAkIgIgCQgGgCgEgFIAKgOIAGAEQAEACAGAAQAFAAAEgCQADgCABgEIgZAAIAAgOIAZAAQgCgDgDgCQgEgCgEAAQgFAAgEABIgIAEIgIgOQACgDAJgEQAHgCAHAAQAHAAAHACQAHACAFAFQAFAEACAGQACAGAAAHQAAAHgCAGQgCAGgEAEQgFAFgHACQgGADgIAAgAq/AjQgGgBgEgEIgHgHQgDgEgCgFIgIAAIAAAVIgWAAIAAg+IAWAAIAAAVIAJAAQACgFADgEIAHgHQAEgDAFgCQAFgBAGAAQAIAAAHACQAGADAFAEQAEAFADAGQACAGAAAGQAAAHgCAGQgDAGgEAEQgFAFgGACQgHADgIAAQgGAAgFgCgAq7gEQgCADAAAFQAAAGACADQADADAFAAQAFAAADgDQACgDAAgGQAAgFgCgDQgDgDgFAAQgFAAgDADgAvHAjQgGgDgFgEQgEgFgDgGQgCgGAAgHQAAgGACgGQADgGAEgFQAFgEAGgDQAHgCAIAAQAFAAAGACQAFACAEAEQAFAEACAFQADAGAAAFQAAAHgCAEIgpAAQABAEAEACQAEACAFAAQAIAAAJgEIAGAPQgFADgHACQgFACgHAAQgJAAgGgCgAuvgCQAAgEgCgCQgDgDgFAAQgFAAgEACQgCACgCAFIAXAAIAAAAgAzXAiQgGgCgFgFQgEgEgDgGQgDgGABgHQgBgGADgGQADgGAEgFQAFgEAGgDQAGgCAJAAQAHAAAHACQAGADAGAEQAEAFACAGQADAGAAAGQAAAHgDAGQgCAGgEAEQgGAFgGACQgHADgHAAQgJAAgGgDgAzRgFIgDAEIgBAFQAAAGAEAEQADADAGAAQAFAAAEgDIACgFIABgFQAAgFgDgEQgEgEgFAAQgFAAgEAEgAKjAjIgGgEQgDgDgBgDQgCgEAAgFQAAgFACgEQACgEADgDQADgBAEgBQAEgCAFAAQAGAAAGAEQAAgGgCgCQgCgDgEAAIgKABIgGADIgGgPIAKgFIAOgBQAGAAAGABQAFACADAEQADADACAFQABAFAAAGIAAAlIgSAAIAAgFQgCADgFABQgEACgGAAIgIgBgAKuALQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAABQABAAAAAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAQAGAAACgEIAAgEQgDgCgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABgAGVAjIgHgEQgDgDgBgDQgBgEAAgFQAAgFACgEQABgEADgDQAEgBADgBQAEgCAFAAQAGAAAGAEQABgGgDgCQgCgDgEAAIgKABIgGADIgGgPIALgFIANgBQAHAAAFABQAFACADAEQADADACAFQACAFAAAGIAAAlIgTAAIAAgFQgCADgEABQgFACgFAAIgIgBgAGfALQAAAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAQABABAAAAQABAAABAAQAFAAACgEIAAgEQgDgCgEAAQgBAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBABgAgmAjIAAg+IAbgBIALABQAGABADACQAFADACADQACADAAAEQgBAGgDAEQgDACgEABIAAAAQAFACAEAEQADADAAAFQAAAFgCAEQgCAEgEACQgEADgGABQgEABgIAAgAgRATIAJAAQAAAAABAAQAAAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBIgFgBIgHAAgAgRgKIAAAIIAHAAIAEgBQABAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAIgBgDQAAgBgBAAQAAAAgBAAQAAgBgBAAQgBAAAAAAgAVlAjIgUgeIAAAeIgUAAIAAhhIAUAAIAAA+IASgbIAaAAIgUAcIAXAigAR1AjIgVg+IgUA+IgVAAIgdhhIAZAAIARA+IASg+IAXAAIATA+IARg+IAVAAIgcBhgAOdAjIAAgiQAAgEgEgDQgCgCgFAAIgFABIgFADIAAAnIgVAAIAAg+IAVAAIAAAFIAHgEQAEgCAEAAIALABIAIAFQAEADACAFQABAGAAAHIAAAkgANNAjIAAg+IAVAAIAAA+gAMpAjIAAgjQAAgEgCgCQgCgCgEAAIgHABQgCACgBACIAAAmIgVAAIAAgjQAAgEgCgCQgBgCgEAAIgGABIgEAEIAAAmIgWAAIAAg+IAWAAIAAAGQADgDAFgCQAFgCAGAAQAGAAAFADQAFACABAEQAEgEAFgCQAEgDAIAAIAIABIAFAEQAEADABAEQACAFgBAGIAAAogAH3AjIAAgiQAAgEgEgDQgCgCgFAAIgFABIgFADIAAAnIgVAAIAAg+IAVAAIAAAFIAHgEQAEgCAEAAIALABIAIAFQAEADACAFQABAGAAAHIAAAkgAFmAjIAAg+IAVAAIAAA+gAB3AjIgXgiIgIAAIAAAiIgXAAIAAhhIAiAAQAGAAALACQAGADAEAEQAFAEACAGQABAFABAHQgBAHgBAFQgCAFgDADIgFAGIgFADIAcAlgABYgTIAIAAQAGAAAFgDIACgDQACgCAAgDQAAgFgDgDIgEgCIgGgBIgKAAgAimAjIAAgpIgSAAIAAgVIA5AAIAAAVIgSAAIAAApgAluAjIAAgqIgTAAIAAAqIgVAAIAAg+IA+AAIAAA+gAn8AjIgUgdIAAAdIgUAAIAAg+IAUAAIAAAcIASgcIAaAAIgUAdIAXAhgAsXAjIAAghIgXAhIgVAAIAAg+IAVAAIAAAgIAXggIAVAAIAAA+gAtnAjIAAgVIgUAAIAAAVIgVAAIAAg+IAVAAIAAAWIAUAAIAAgWIAVAAIAAA+gAv7AjIAAgVIgVAAIAAAVIgVAAIAAg+IAVAAIAAAWIAVAAIAAgWIAVAAIAAA+gAxJAjIAAgfIgQASIAAAAIgQgSIAAAfIgVAAIAAg+IATAAIATAWIARgWIATAAIAAA+gA0MAjIAAgqIgUAAIAAAqIgVAAIAAg+IA+AAIAAA+gA1oAAQgDgCABgEQgBgFADgDQADgDAFAAQADAAAEADQACADAAAFQAAAEgCACQgEADgDAAQgFAAgDgDgA1TgLQgDgDAAgFQAAgEADgDQACgDAFAAQAEAAADADQADADAAAEQAAAFgDADQgDADgEAAQgFAAgCgDgA18gLQgDgDAAgFQAAgEADgDQADgDAEAAQAEAAADADQAEADAAAEQAAAFgEADQgDADgEAAQgEAAgDgDgA1TgjQgDgDAAgEQAAgEADgDQACgDAFAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgFAAgCgDgA18gjQgDgDAAgEQAAgEADgDQADgDAEAAQAEAAADADQAEADAAAEQAAAEgEADQgDADgEAAQgEAAgDgDgANPgnQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgCgCAAgDQAAgGAEgDQADgDAGAAQAEAAAEADQAEADAAAGQAAAFgEAEQgDADgFAAQgGAAgDgDgAFognQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgCgCAAgDQAAgGAEgDQAEgDAFAAQAFAAADADQAEADAAAGQAAAFgEAEQgDADgFAAQgFAAgEgDgA1oguQgCgDAAgEQAAgEACgDQAEgDAEAAQAEAAADADQADADAAAEQAAAEgDADQgDADgEAAQgEAAgEgDg");
	this.shape.setTransform(140.8,6.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ53, new cjs.Rectangle(0,0,281.6,12.9), null);


(lib.Символ52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#014474").s().p("EgkYAC4IgBlvMBIzAAAIh0Fvg");
	this.shape.setTransform(233,18.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ52, new cjs.Rectangle(0,0,466,36.9), null);


(lib.Символ51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGNBoIAAgeIhsAAIAAAeIgmAAIAAhEIASAAIAHgLIAIgWQAEgNADgQQADgTABgUIABgjIByAAIAACIIAZAAIAABEgAFMghQgEAfgDALQgHAVgEAGIA5AAIAAhjIgjAAgAB+BLQgJgBgIgDQgJgDgHgFQgIgFgGgFQgGgGgFgIQgFgGgEgJQgDgIgBgJQgDgJAAgKQAAgKACgJIAFgRQAEgIAEgHQAFgIAGgGQAGgGAIgFQAHgEAIgEQAJgDAJgCQAKgCALAAQAJAAAKACQAJABAJADIAQAIIANAKQAGAHAFAHQAFAGADAJQAEAJACAIQABAKAAALQAAAJgBAJQgCAIgEAJQgDAIgFAHQgFAHgGAHIgNAKIgQAJIgSAEQgKACgJAAQgKAAgKgCgAB9g+QgJAEgGAHQgIAHgDAJQgEALAAAMQAAAKAEAKQAEAJAHAHQAHAIAJADQAJAEALAAQAMAAAJgEQAKgDAGgIQAHgHADgKQADgJAAgKQAAgMgEgLQgEgJgGgHQgHgHgJgEQgKgDgKAAQgLAAgKADgAm7BKQgHgBgFgDQgGgDgEgFQgGgFgDgFQgGgIgGgUQgCgMgBgYQAAgOADgYQACgKAKgSQADgFAFgFQAFgEAGgEQAFgDAGgBQAIgCAHAAQAIAAAGACQAHABAGADQAFAEAFAEIAJAKQAIASADAKQADAYAAAOQgBAYgCAMQgGAUgFAIIgIAKQgFAFgGADQgGADgGABQgHACgHAAQgIAAgHgCgAm2hAQgEADgDAGQgCAGgBALIgCAaQAAAOACAKQABAKADAHQADAGAEADQAEADAFAAQAFAAAEgDQAEgCACgHQACgHACgKIAAgyQgCgLgDgGQgCgGgDgDQgFgDgFAAQgGAAgDADgAJCBKIgPglIhFAAIgOAlIgpAAIBJiuIAkAAIBJCugAIkAAIgTgxIgUAxIAnAAgAg9BKIAAiuIBjAAIAAAlIg8AAIAACJgAjxBKIA3iJIhGAAIAAglIBzAAIAAAaIg8CUgAlBBKIAAh4IgSALIgTgeIAvgjIAbAAIAACugApsBKIAAgeIAWgWQAOgNAIgJQALgNAFgLIAGgMIABgLQAAgJgFgFQgDgDgIAAQgHgBgFAGQgEAEgDAKIgfgPQABgKAFgHQAEgIAIgFQAHgGAIgDQAKgDAMAAQAMAAAKAEQAJAEAHAGQAHAHACAJQAEAIAAAJQAAAyg6AsIBAAAIAAAjg");
	this.shape.setTransform(62.1,10.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ51, new cjs.Rectangle(0,0,124.2,20.8), null);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AXmBuQgJgBgJgEQgIgDgHgFQgIgFgFgGQgGgFgFgHQgFgIgDgIIgGgRQgBgKAAgKQAAgJABgJIAFgQIAHgQQAEgHAGgGQAGgGAHgFQAHgFAJgEQAIgDALgBQAKgCAKAAQAMgBAUAGQANAEAJAJIgSAdIgPgHQgKgDgLAAQgJAAgKADQgIAEgHAGQgHAIgEAJQgDAJAAANQAAALADAKQAEAKAHAHQAHAHAKAEQAKAEAMAAQAJAAAKgDQAKgDAIgHIAQAfQgEADgGAEIgOAHQgWAFgLABQgKgBgKgBgAQiBuQgJgBgJgEQgIgDgIgFQgHgEgGgGQgGgFgFgIQgFgHgDgIQgEgJgCgJQgBgJAAgLQgBgJACgJIAFgQQADgJAFgHQAFgHAGgGQAGgGAHgFQAIgFAJgEQAIgDAKgBQAJgCAKAAQALAAAJABQAJABAIADIAQAIQAIAFAGAGQAGAGAFAHQAFAHAEAJQADAIABAIQACAJAAALQAAAKgCAJQgBAJgDAJQgEAHgFAIQgFAHgGAGIgOALIgQAIIgRAFQgJABgLABQgKgBgJgBgAQigbQgKAEgHAGQgGAIgEAJQgEAKAAALQAAALAEAKQAEAJAHAIQAHAHAJAEQAJAEAKAAQANAAAKgEQAIgEAHgHQAHgIADgJQADgKAAgLQAAgLgEgKQgEgJgHgIQgGgGgKgEQgJgEgLAAQgKAAgJAEgALQBuQgJgBgJgEQgIgDgHgFQgHgFgHgGQgFgFgFgHQgFgIgEgIIgEgRQgCgKAAgKQAAgJACgJIAEgQIAHgQQAFgHAFgGQAGgGAHgFQAHgFAJgEQAIgDAKgBQALgCALAAQALgBAUAGQANAEAJAJIgSAdIgPgHQgKgDgKAAQgKAAgKADQgIAEgHAGQgHAIgDAJQgFAJAAANQAAALAFAKQADAKAHAHQAHAHAKAEQAKAEAMAAQAJAAAKgDQAKgDAIgHIAQAfQgEADgGAEIgOAHQgVAFgMABQgLgBgJgBgAqtBsIAAiuIBqAAIAAAmIhCAAIAAAcQAHgBANgBQAMABALACQAKAEAIAHQAHAHAFAKQAEAKAAAMQAAAOgEALQgFALgJAHQgJAIgMADQgNAEgQABIgxgCgAqFAkIAAAjIAPABQALAAAGgFQAFgEAAgJQAAgIgFgFQgFgGgLAAgA9RBsIABgnQAGAAAFgBQAGgDAFgJQAFgKADgVQACgOAEgpIAEgkIB0AAIAACuIgpAAIAAiIIgmAAIgEAgQgGApgEAPIgHATIgIAPQgFAFgFAEQgFAEgGABQgGACgHAAgEggLABsIAAitIA1gBQAPAAAMADQAKADAIAGQAHAGAEAIQADAIAAAJQAAANgGAKQgEAIgKAHIAAAAIAJAGQAFADADAFQADAFACAHQADAGAAAJQAAANgFAKQgFALgKAGQgIAHgMADQgNAEgOAAQgiAAgQgCgA/jBGQAGACAHAAQAMAAAGgFQAFgEABgKQgBgHgFgEQgGgEgJAAIgQAAgA/jgcIAAAfIANAAQAJAAAFgDQAEgFAAgIQABgIgGgEQgFgEgJAAgAfkBsIAAhsIhOBsIgjAAIAAiuIApAAIAABsIBNhsIAjAAIAACugAb+BsIAAiIIg1AAIAAgmICSAAIAAAmIg1AAIAACIgAZOBsIAAiuIBnAAIAAAmIg/AAIAAAeIA4AAIAAAmIg4AAIAAAfIBDAAIAAAlgAUkBsIAAhsIhOBsIgjAAIAAiuIAoAAIAABsIBNhsIAjAAIAACugAOcBsIg8hTIAABTIgoAAIAAiuIAoAAIAABLIA6hLIAvAAIhBBQIBHBegAH4BsIAAiuIA1AAQAOAAAUAFQAJADANAKQAIAHAEALQADAKAAAMQAAALgEALQgFAKgIAIQgJAJgLAEQgMAFgPAAIgUgBIAAA7gAIggcIAAAnIASACQAKgBAGgEIAFgGQACgEAAgHQAAgFgBgEQgCgDgDgDQgGgEgLgBgAFoBsIAAiuIBoAAIAAAmIg/AAIAAAeIA4AAIAAAmIg4AAIAAAfIBCAAIAAAlgAEfBsIg7hTIAABTIgpAAIAAiuIApAAIAABLIA5hLIAvAAIhBBQIBHBegAAsBsIAAiuIBoAAIAAAmIhAAAIAAAeIA5AAIAAAmIg5AAIAAAfIBCAAIAAAlgAgoBsIAAhuIgxBEIgFAAIgxhDIAABtIgoAAIAAiuIAoAAIA2BJIAzhJIAmAAIAACugAkABsIg8hTIAABTIgoAAIAAiuIAoAAIAABLIA6hLIAvAAIhBBQIBGBegAn6BqQgHgDgEgCIAOgiQAGAEAGAAQAFAAADgCQADgCACgDIACgFIhLh9IAtAAIAyBVIAjhVIAoAAIg7CFQgEALgFAHQgGAHgGAGQgGAFgHADQgHACgKAAQgHAAgIgCgAs0BsIAAhsIhNBsIgjAAIAAiuIAnAAIAABsIBOhsIAjAAIAACugAw0BsIAAiuIBnAAIAAAmIg/AAIAAAeIA4AAIAAAmIg4AAIAAAfIBDAAIAAAlgA0uBsIAAiuIAoAAIAACJIAqAAIAAiJIApAAIAACJIAqAAIAAiJIAoAAIAACugA2CBsIAAhCQgGAEgJADQgLADgMgBQgKABgKgDQgKgDgHgGQgIgHgEgKIgDgMIgCgOIAAg/IAoAAIAAAzQAAAKACAFQACAGAEADQAEAEANABQAHAAAGgCQAHgCAHgFIAAhHIAnAAIAACugA5vBqQgIgDgDgCIAOgiQAGAEAGAAQAFAAADgCQAEgCABgDIADgFIhMh9IAtAAIAyBVIAjhVIAoAAIg6CFQgFALgFAHQgFAHgHAGQgGAFgHADQgHACgKAAQgHAAgIgCgATthKQgKgCgGgGQgIgFgDgHQgDgHgBgKIAmAAQAAAIAEACQADADAJAAQAHAAADgCQAEgDAAgIIAmAAQgBAKgDAHQgDAIgIAEQgGAGgKACQgKADgLAAQgNAAgKgDgAtrhKQgKgCgGgGQgHgFgEgHQgDgHAAgKIAmAAQAAAIADACQADADAJAAQAIAAADgCQAEgDgBgIIAmAAQAAAKgDAHQgEAIgHAEQgHAGgKACQgKADgLAAQgMAAgLgDg");
	this.shape.setTransform(206,11.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ50, new cjs.Rectangle(0,0,412,22.3), null);


(lib.Символ49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHEBuIAAiuIBnAAIAAAmIg/AAIAAAdIA4AAIAAAmIg4AAIAAAgIBCAAIAAAlgAFOBuIAAiIIg0AAIAAgmICRAAIAAAmIg1AAIAACIgADZBuIAAhtIhOBtIgjAAIAAiuIAoAAIAABsIBOhsIAjAAIAACugAAnBuIgOgkIhEAAIgPAkIgoAAIBJiuIAiAAIBJCugAAKAkIgTgxIgUAxIAnAAgAjoBuIAAiuIA1gBQAOABAUAEQAJADANAKQAIAIADAKQAEAKAAANQAAALgEAKQgFALgIAHQgJAJgLAFQgNAEgPAAIgTgBIAAA8gAjAgaIAAAmIASACQAKAAAGgEIAFgHQACgEAAgGQAAgFgBgEQgCgEgDgDQgGgEgMAAgAloBuIAAiuIBkAAIAAAmIg8AAIAACIgAm9BuIAAhtIhNBtIgjAAIAAiuIAoAAIAABsIBNhsIAjAAIAACugACihIQgKgCgGgGQgHgFgEgIQgDgHAAgJIAlAAQAAAHAEADQADACAJABQAHAAAEgCQADgEAAgHIAmAAQAAAJgEAHQgDAIgHAFQgHAGgKACQgKADgLAAQgNAAgKgDg");
	this.shape.setTransform(55.8,11);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ49, new cjs.Rectangle(0,0,111.7,22), null);


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.kokorin();
	this.instance.parent = this;
	this.instance.setTransform(0,0,1.208,1.208);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ47, new cjs.Rectangle(0,0,368.6,362.5), null);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.shved();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.849,0.849);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ45, new cjs.Rectangle(0,0,269,275), null);


(lib.Символ44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003E6B").s().p("A8bFsICCl7IABAAICAlcMAqVAAAIiBFcIMgAAIiCF7g");
	this.shape.setTransform(182,36.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ44, new cjs.Rectangle(0,0,364,72.8), null);


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AzTB9IAAgeIhsAAIAAAeIgmAAIAAhDIATAAIAHgNIAIgVQAEgOACgPQAEgTABgUIABgjIByAAIAACJIAYAAIAABDgA0TgMQgFAegDANQgGAUgFAHIA5AAIAAhjIgjAAgAPzBgQgJgBgJgDQgIgDgIgFQgHgFgGgGQgGgFgFgIQgFgHgDgJIgFgRQgCgKABgKQgBgIACgJIAEgRIAHgPQAFgHAFgHQAGgGAIgEQAHgFAJgEQAIgEAKgBQAKgCALAAQAMAAATAGQAOAEAJAIIgSAeIgQgHQgJgEgLAAQgKAAgJAEQgJADgHAHQgGAHgEAKQgEAKAAALQAAAMAEAKQAEAKAGAGQAIAIAJAEQALADALAAQAKAAAKgCQAJgEAJgGIAPAeQgDAEgHAEIgNAHQgWAFgMAAQgKAAgJgCgAJgBgQgJgBgIgDQgJgDgHgFQgIgEgFgGQgHgGgEgIQgGgGgDgJQgDgIgCgKQgCgJAAgLQAAgIABgJIAGgRQADgIAFgHQAEgHAHgHQAFgGAIgEQAHgFAJgEQAIgEAKgBQAJgCALAAQAKAAAJABQAJACAJADIAQAIIAOALQAGAFAFAHQAEAIAEAIQAEAIABAJQACAKAAAJQAAALgCAIQgBAJgEAJQgEAIgEAHQgFAIgGAFIgOAMIgQAIIgSAEQgJACgKAAQgKAAgKgCgAJggoQgKADgGAHQgHAHgEAKQgDAKAAAKQAAAMADAKQAEAJAHAHQAHAHAJAFQAKADAKAAQAMAAAKgDQAJgFAGgHQAHgHAEgKQADgKAAgLQAAgKgFgKQgDgKgHgHQgHgHgJgDQgJgFgLAAQgLAAgJAFgACKBgQgKgBgIgDQgJgDgHgFQgIgFgFgGQgHgFgEgIQgFgHgEgJIgEgRQgCgKAAgKQAAgIACgJIAEgRIAHgPQAEgHAGgHQAGgGAHgEQAHgFAJgEQAJgEAKgBQAJgCAMAAQALAAAUAGQAOAEAIAIIgSAeIgPgHQgJgEgLAAQgLAAgIAEQgKADgGAHQgHAHgDAKQgEAKgBALQABAMAEAKQADAKAHAGQAHAIAKAEQAKADALAAQAKAAAKgCQAKgEAJgGIAOAeQgDAEgGAEIgNAHQgXAFgLAAQgLAAgIgCgAoyBgQgJgBgJgDQgIgDgIgFQgHgFgGgGQgGgFgEgIQgGgHgDgJIgFgRQgCgKABgKQgBgIACgJIAFgRIAGgPQAFgHAFgHQAGgGAIgEQAHgFAJgEQAIgEAKgBQAKgCALAAQALAAAVAGQANAEAIAIIgSAeIgPgHQgJgEgLAAQgKAAgJAEQgJADgHAHQgGAHgEAKQgEAKAAALQAAAMAEAKQAEAKAGAGQAHAIAKAEQALADALAAQAKAAAKgCQAJgEAJgGIAPAeQgDAEgHAEIgNAHQgWAFgMAAQgKAAgJgCgATxBfIAAitIA1gCQAOAAANAEQAKACAIAHQAGAGAEAHQADAIAAAJQABAOgGAKQgFAJgKAGIAAAAIAJAFQAFAEADAEQAEAFACAHQACAHAAAIQAAANgFALQgEAKgKAHQgIAGgNAEQgMADgOAAQgjAAgPgBgAUYA5QAGABAIABQALAAAHgGQAFgEAAgJQAAgIgFgEQgGgEgKAAIgQAAgAUYgpIAAAfIAOAAQAIAAAFgDQAFgFAAgJQAAgHgGgEQgFgEgIAAgAsIBfIAAitIA1gCQAPAAAMAEQAKACAIAHQAHAGADAHQAEAIAAAJQAAAOgGAKQgEAJgKAGIAAAAIAJAFQAFAEADAEQAEAFACAHQACAHAAAIQAAANgFALQgFAKgKAHQgIAGgMAEQgMADgOAAQgkAAgPgBgArgA5QAGABAHABQAMAAAGgGQAGgEAAgJQAAgIgGgEQgGgEgKAAIgPAAgArggpIAAAfIANAAQAIAAAGgDQAEgFAAgJQAAgHgFgEQgFgEgJAAgAyjBfIABgoQAGABAFgCQAFgCAFgKQAFgKAEgUQACgNAEgrIADgjIB0AAIAACuIgpAAIAAiIIgmAAIgDAgQgHApgDAPIgHATIgJAOQgEAFgFAEQgGAEgFACQgGABgIAAgAR7BfIAAiIIg1AAIAAgmICRAAIAAAmIg0AAIAACIgANiBfIAAhsIhOBsIgjAAIAAiuIApAAIAABsIBNhsIAjAAIAACugAGHBfIAAiuIA2gBQANABAUAEQAJADANAKQAIAIADAKQAEAKAAANQAAAMgEAJQgFALgIAHQgIAJgMAFQgMAEgPAAIgUgBIAAA8gAGvgpIAAAnIASACQAKAAAGgEIAGgHQABgFAAgGQAAgFgBgEQgCgEgDgDQgGgEgMAAgAESBfIAAiIIg1AAIAAgmICRAAIAAAmIg1AAIAACIgAhIBdQgHgDgEgDIAPgiQAGAFAFAAQAFgBADgBQAEgCACgEIACgFIhMh8IAtAAIAyBVIAjhVIAnAAIg5CEQgFALgEAHQgGAIgGAGQgGAEgIAEQgHACgKAAQgGAAgJgCgAjYBfIgmg7IglA7IguAAIA5hZIg3hVIAvAAIAjA4IAjg4IAvAAIg5BVIA7BZgAnLBfIAAiuIBoAAIAAAmIg/AAIAAAeIA4AAIAAAlIg4AAIAAAgIBCAAIAAAlgAuPBfIAAg4IgSAAIghA4IgsAAIAohBQgFgDgFgFQgFgFgEgFQgEgHgCgGQgCgHAAgJQAAgMAFgLQAEgMAJgIQAEgGAGgCQAGgEAHgDQAIgCAIgBQAJgCAKAAIAvABIAACugAuuglQgEADgCAFQgCAFAAAEQAAAJAFAHQAFAEAJACIAUAAIAAgrIgOgBQgLAAgGAFgAMshXQgKgCgHgGQgHgFgDgIQgEgHAAgJIAlAAQAAAHAEADQAEACAIABQAHAAAEgCQADgEABgHIAlAAQAAAJgDAHQgEAIgHAFQgHAGgJACQgKADgMAAQgNAAgJgDg");
	this.shape.setTransform(138.2,12.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ43, new cjs.Rectangle(0,0,276.3,25), null);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah3BZQgJgCgJgDQgIgDgIgEQgHgFgGgGQgGgGgFgHQgFgHgEgJQgDgIgCgJQgCgKAAgKQAAgIACgKIAFgRQADgHAFgIQAFgHAGgGQAGgGAHgFQAIgFAIgDQAJgEAJgCQAKgCAKAAQAKABAKABQAJABAIAEIAQAIIAOAKQAGAGAFAHQAFAHADAJQAEAIABAJQACAKAAAJQAAAKgCAJQgBAJgEAIQgDAJgFAHQgFAHgGAGIgOALIgQAIIgRAFQgKACgKgBQgKABgJgCgAh4gwQgJADgHAIQgHAGgDAKQgEALAAAKQAAALAEAKQAEAKAHAGQAGAIAKAEQAJAEAKAAQAMAAAKgEQAJgEAHgIQAGgGAEgLQADgJAAgLQAAgKgEgLQgEgKgHgGQgHgIgJgDQgJgEgLAAQgLAAgJAEgAl9BYIABgpQAGABAFgCQAGgCAEgJQAFgKAEgUQACgOAEgrIADgjIB0AAIAACvIgoAAIAAiJIgmAAIgEAhQgGApgEAOIgHAUIgJANQgEAGgFAEQgFADgGACQgGABgHABgAMeBYIAAivIBnAAIAAAmIg/AAIAAAfIA4AAIAAAkIg4AAIAAAgIBCAAIAAAmgALJBYIAAhsIhOBsIgjAAIAAivIAoAAIAABsIBOhsIAjAAIAACvgAIDBYIAAhHIg/AAIAABHIgoAAIAAivIAoAAIAABEIA/AAIAAhEIApAAIAACvgAEMBYIAAivIBoAAIAAAmIhAAAIAAAfIA5AAIAAAkIg5AAIAAAgIBDAAIAAAmgADIBYIg4hUIAABUIgoAAIAAhUIg4BUIguAAIBAhbIg9hUIAuAAIA1BNIAAhNIAoAAIAABNIA1hNIAuAAIg9BUIBABbgAnABYIAAhsIhOBsIgjAAIAAivIAoAAIAABsIBOhsIAjAAIAACvgArNBYIAAivIA1AAQAOAAAUAFQAJADANAJQAIAJADAKQAEAKAAAMQAAAMgEAKQgFAKgIAIQgJAIgLAFQgNAFgPAAIgTgBIAAA8gAqlgxIAAAoIASABQAKAAAGgEIAFgGQACgFAAgGQAAgGgBgEQgCgDgDgDQgGgFgMAAgAsiBYIAAiJIg9AAIAACJIgoAAIAAivICNAAIAACvg");
	this.shape.setTransform(90.4,9.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ42, new cjs.Rectangle(0,0,180.9,18.1), null);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.shved();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.966,0.966);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ41, new cjs.Rectangle(0,0,306.2,313), null);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.samsung();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.81,0.81);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ39, new cjs.Rectangle(0,0,85.1,141.8), null);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.iphone();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.81,0.81);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ38, new cjs.Rectangle(0,0,86.7,130.4), null);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.seif();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.458,0.458);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ36, new cjs.Rectangle(0,0,119.5,156.6), null);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003E6B").s().p("A6gFaIBkk/Ig/AAIBtl0MAvoAAAIhdE/IEkAAIh1F0g");
	this.shape.setTransform(169.7,34.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ34, new cjs.Rectangle(0,0,339.5,69.2), null);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AwyBZQgJgCgJgDQgIgDgIgEQgHgFgGgGQgGgGgFgHQgFgHgEgJQgDgIgCgJQgCgKAAgKQAAgIACgKIAFgRQADgHAFgIQAFgHAGgGQAGgGAHgFQAIgFAIgDQAJgEAJgCQAKgCAKAAQAKABAKABQAJABAIAEIAQAIQAHAEAHAGQAGAGAFAHQAFAHADAJQAEAIABAJQACAKAAAJQAAAKgCAJQgBAJgEAIQgDAJgFAHQgFAHgGAGIgOALIgQAIIgRAFQgKACgKgBQgKABgJgCgAwzgwQgJADgHAIQgHAGgDAKQgEALAAAKQAAALAEAKQAEAKAHAGQAGAIAKAEQAJAEAKAAQAMAAAKgEQAJgEAHgIQAGgGAEgLQADgJAAgLQAAgKgEgLQgEgKgHgGQgHgIgJgDQgJgEgLAAQgLAAgJAEgAgLBXIAAitIA0gCQAPABAMADQALADAHAGQAHAGAEAIQADAHAAAKQAAANgFAKQgFAJgKAHIAAAAIAJAFQAFADADAFQAEAFACAGQACAIAAAIQAAANgFALQgFAJgJAHQgJAHgMADQgMADgOABQgjgBgPgBgAAcAyQAGABAIAAQALAAAGgFQAGgFAAgIQAAgIgGgFQgFgDgKAAIgQAAgAAcgxIAAAgIAOAAQAIAAAFgEQAFgEAAgKQAAgGgGgFQgFgEgIAAgAr5BYIABgpQAGABAFgCQAGgCAEgJQAFgKAEgUQACgOAEgrIADgjIB0AAIAACvIgoAAIAAiJIgmAAIgEAhQgGApgEAOIgHAUIgJANQgEAGgFAEQgFADgGACQgGABgHABgAPNBYIAAivIAoAAIAAA3IAPgBQAQAAAMAFQAMAEAIAHQAIAIAEAKQAEAKAAAOQAAAOgFAMQgFALgJAJQgJAIgNAEQgUAFgLAAgAP1AFIAAAtIALABQAHAAAEgCQAFgCADgDQADgCACgFQABgFAAgGQAAgFgBgFIgFgHQgHgFgLAAgARVBYIAAivIAoAAIAACvgAN4BYIAAhvIgxBDIgGAAIgwhCIAABuIgoAAIAAivIAoAAIA2BLIAzhLIAmAAIAACvgAJiBYIAAhvIgxBDIgGAAIgwhCIAABuIgoAAIAAivIAoAAIA2BLIAzhLIAmAAIAACvgAFDBYIAAivIBoAAIAAAmIhAAAIAAAfIA5AAIAAAkIg5AAIAAAgIBDAAIAAAmgAECBYIgOglIhFAAIgPAlIgoAAIBJivIAjAAIBJCvgADlAOIgUgxIgUAxIAoAAgAhgBYIAAhsIhNBsIgjAAIAAivIAoAAIAABsIBNhsIAjAAIAACvgAklBYIAAhEQgGAFgJADQgKACgMAAQgLAAgJgCQgKgDgHgGQgIgHgEgLIgEgKIgBgPIAAg/IAoAAIAAAzQAAAJACAHQACAFADAEQAFAEAMABQAHAAAHgCQAHgDAGgEIAAhIIAoAAIAACvgAm8BYIgPglIhFAAIgOAlIgpAAIBJivIAkAAIBJCvgAnaAOIgTgxIgUAxIAnAAgAs8BYIAAiJIg9AAIAACJIgoAAIAAivICNAAIAACvg");
	this.shape.setTransform(114.9,9.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ33, new cjs.Rectangle(0,0,229.8,18.1), null);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlBBZQgKgCgIgDQgIgDgIgEQgHgGgGgGQgGgFgEgHQgFgIgEgIIgFgSQgBgJgBgKQABgIABgKIAFgRIAHgPQAEgHAGgGQAGgGAGgFQAIgFAJgDQAIgEAKgCQAKgCALAAQALABAVAFQANAEAIAIIgSAeIgOgHQgKgDgLAAQgKAAgJAEQgJADgHAHQgGAGgEAKQgEALAAALQAAALAEAKQAEAKAGAHQAIAHAJAEQAKAEAMAAQAJAAALgDQAKgDAIgGIAPAeQgDADgGAFIgOAGQgWAFgMAAQgKABgJgCgAq/BZQgJgCgJgDQgIgDgIgEQgHgFgHgGQgFgGgGgHQgEgHgEgJQgDgIgCgJQgCgKAAgKQAAgIACgKIAEgRQAEgHAFgIQAFgHAFgGQAHgGAHgFQAHgFAJgDQAIgEAKgCQAKgCAKAAQAKABAJABQAKABAIAEIAQAIQAHAEAGAGQAHAGAEAHQAGAHADAJQADAIACAJQACAKAAAJQAAAKgCAJQgCAJgDAIQgDAJgGAHQgEAHgHAGIgNALIgQAIIgSAFQgJACgKgBQgKABgJgCgArAgwQgKADgGAIQgHAGgDAKQgFALAAAKQAAALAFAKQADAKAIAGQAGAIAKAEQAJAEAKAAQAMAAAKgEQAJgEAGgIQAHgGADgLQADgJAAgLQAAgKgEgLQgDgKgHgGQgHgIgJgDQgJgEgLAAQgLAAgJAEgAioBXIAAitIA1gCQAPABAMADQALADAHAGQAIAGADAIQAEAHAAAKQAAANgGAKQgFAJgKAHIAAAAIAJAFQAFADADAFQAEAFACAGQADAIgBAIQABANgGALQgFAJgJAHQgJAHgMADQgMADgOABQgjgBgQgBgAh/AyQAFABAIAAQAMAAAFgFQAGgFAAgIQAAgIgGgFQgFgDgKAAIgPAAgAh/gxIAAAgIANAAQAIAAAFgEQAFgEAAgKQAAgGgFgFQgGgEgIAAgAvFBYIABgpQAGABAFgCQAFgCAFgJQAFgKADgUQADgOAEgrIADgjIB0AAIAACvIgpAAIAAiJIgmAAIgDAhQgHApgDAOIgHAUIgJANQgEAGgFAEQgFADgGACQgHABgHABgAKwBYIAAivIAoAAIAAA3IAQgBQAQAAAMAFQALAEAJAHQAHAIAEAKQAEAKAAAOQAAAOgFAMQgFALgIAJQgKAIgNAEQgUAFgLAAgALYAFIAAAtIALABQAHAAAEgCQAFgCADgDQADgCACgFQABgFABgGQgBgFgBgFIgFgHQgGgFgMAAgAgOBYIAAivIAoAAIAAA3IAPgBQAQAAAMAFQAMAEAIAHQAIAIAEAKQAEAKAAAOQAAAOgFAMQgFALgJAJQgKAIgNAEQgTAFgLAAgAAaAFIAAAtIALABQAGAAAFgCQAEgCAEgDQADgCACgFQABgFAAgGQAAgFgBgFIgGgHQgGgFgMAAgAT7BYIgOglIhGAAIgOAlIgpAAIBJivIAkAAIBJCvgATdAOIgTgxIgUAxIAnAAgAONBYIAAivIAoAAIAACJIAqAAIAAiJIApAAIAACJIAqAAIAAiJIAoAAIAACvgAM4BYIAAivIAoAAIAACvgAITBYIAAivIA2AAQANAAAVAFQAIADANAJQAJAJADAKQADAKABAMQAAAMgFAKQgEAKgIAIQgJAIgLAFQgNAFgPAAIgUgBIAAA8gAI7gxIAAAoIASABQALAAAFgEIAGgGQACgFAAgGQAAgGgBgEQgCgDgEgDQgFgFgMAAgAGUBYIAAivIBkAAIAAAmIg8AAIAACJgAE/BYIAAhsIhNBsIgjAAIAAivIAnAAIAABsIBOhsIAjAAIAACvgAB5BYIAAivIApAAIAACvgAouBYIAAivIBkAAIAAAmIg9AAIAACJgAv1BYIgOglIhFAAIgPAlIgoAAIBJivIAjAAIBJCvgAwSAOIgTgxIgUAxIAnAAgAy+BYIAAhHIg/AAIAABHIgoAAIAAivIAoAAIAABEIA/AAIAAhEIApAAIAACvg");
	this.shape.setTransform(131.8,9.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ32, new cjs.Rectangle(0,0,263.6,18.1), null);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.kaprizov();
	this.instance.parent = this;
	this.instance.setTransform(0,0,1.128,1.128);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ31, new cjs.Rectangle(0,0,245.9,304.6), null);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.kaprizov();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ30, new cjs.Rectangle(0,0,218,270), null);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#014474").s().p("A5eFxIDEltIkfAAIDIl1IavAAIjBFuIa9AAIjIF0g");
	this.shape.setTransform(172.2,37);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ27, new cjs.Rectangle(0,0,344.3,73.9), null);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AOmBoIAAgeIh+AAIAAiuIAnAAIAACIIA9AAIAAiIIAnAAIAACIIAZAAIAABEgAtLBoIAAgeIhtAAIAAAeIglAAIAAhEIATAAIAHgLIAHgWQAFgNACgQQADgTABgUIACgjIByAAIAACIIAXAAIAABEgAuLghQgFAfgDALQgGAVgFAGIA4AAIAAhjIgjAAgAFpBLQgKgBgIgDQgJgDgHgFQgIgFgFgGQgHgGgEgHQgFgHgDgIIgFgSQgCgIAAgKQAAgKACgJIAEgRIAHgPQAEgHAGgHQAGgGAHgFQAHgEAJgEQAJgDAKgCQAJgCAMAAQALAAAUAFQAOAFAIAIIgSAeIgPgIQgJgCgLAAQgKgBgJAEQgKADgGAHQgHAHgDAJQgEALAAANQAAALAEAJQADAJAHAIQAHAHAKADQAKAEALAAQAKAAAKgDQAKgDAJgGIAOAeQgDAEgGAEIgNAGQgXAGgLAAQgKAAgJgCgAoIBLQgJgBgIgDQgJgDgHgFQgIgFgFgFQgHgGgEgIQgGgGgDgJQgDgIgCgJQgCgJAAgKQAAgKABgJIAGgRQADgIAFgHQAEgIAHgGQAFgGAIgFQAIgEAIgEQAJgDAJgCQAJgCALAAQAKAAAJACQAJABAJADIAQAIIAOAKQAGAHAFAHQAEAGAEAJQADAJACAIQACAKAAALQAAAJgCAJQgCAIgDAJQgEAIgEAHQgFAHgGAHIgOAKIgQAJIgSAEQgJACgKAAQgKAAgKgCgAoIg+QgJAEgHAHQgHAHgEAJQgDALAAAMQAAAKADAKQAFAJAGAHQAHAIAJADQAKAEAKAAQAMAAAKgEQAJgDAGgIQAHgHADgKQAEgJAAgKQAAgMgFgLQgDgJgHgHQgHgHgJgEQgKgDgKAAQgLAAgJADgAG+BKIABgoQAGABAFgCQAGgCAFgKQAEgKAEgTQADgOAEgrIADgjIB0AAIAACuIgpAAIAAiJIgmAAIgEAiQgGAogEAPIgHATIgIAOQgFAGgFAEQgFADgGABQgGACgHAAgAUcBKIAAhsIhNBsIgjAAIAAiuIAoAAIAABsIBOhsIAjAAIAACugARXBKIAAhsIhNBsIgjAAIAAiuIAnAAIAABsIBOhsIAjAAIAACugALTBKIAAg5IgSAAIgiA5IgsAAIAphBQgGgEgEgEQgFgEgEgGQgEgFgCgHQgCgIAAgJQAAgNAEgLQAEgLAJgIQAFgFAFgDQAHgEAHgDQAHgCAIgBQAKgCAJAAIAvABIAACugAKzg5QgDADgDAEQgBAEAAAFQgBAKAGAFQAFAFAIADIAVAAIAAgtIgPAAQgKgBgHAHgADYBKIAAhHIhAAAIAABHIgoAAIAAiuIAoAAIAABDIBAAAIAAhDIAoAAIAACugAAvBKIgPglIhDAAIgPAlIgoAAIBJiuIAiAAIBJCugAASAAIgTgxIgUAxIAnAAgAjgBKIAAiuIA1AAQAOAAATAEQAKAEANAJQAHAIAEALQAEAKAAALQgBAMgEALQgEAKgIAJQgJAHgMAEQgMAGgPAAIgUgBIAAA7gAi5g/IAAAoIASACQALAAAFgFIAGgGQACgEAAgHQAAgGgBgEQgCgDgEgDQgFgEgMAAgAlWBKIAAiJIg0AAIAAglICQAAIAAAlIg0AAIAACJgAqZBKIAAhsIhOBsIgjAAIAAiuIAoAAIAABsIBNhsIAjAAIAACugAxfBHQgIgCgDgDIAOghQAGADAGAAQAFABADgCQAEgCABgEIADgFIhMh8IAtAAIAyBVIAjhVIAoAAIg6CFQgFAKgFAIQgFAHgHAFQgGAFgHADQgIADgJAAQgHAAgIgDgAy5BKIgOglIhGAAIgOAlIgpAAIBJiuIAkAAIBJCugAzXAAIgTgxIgUAxIAnAAg");
	this.shape.setTransform(134.9,10.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ26, new cjs.Rectangle(0,0,269.7,20.8), null);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhFBoIAAgeIhsAAIAAAeIgmAAIAAhEIATAAIAHgLIAHgWQAFgNACgQQADgTABgUIACgjIByAAIAACIIAYAAIAABEgAiFghQgFAfgDALQgGAVgFAGIA5AAIAAhjIgjAAgADIBLQgJgBgJgDQgIgDgIgFQgHgFgGgFQgGgGgFgIQgFgGgEgJQgDgIgCgJQgCgJAAgKQAAgKACgJIAFgRQADgIAFgHQAFgIAGgGQAGgGAHgFQAIgEAIgEQAJgDAJgCQAKgCAKAAQAKAAAKACQAJABAIADIAQAIIAOAKQAGAHAFAHQAFAGADAJQAEAJABAIQACAKAAALQAAAJgCAJQgBAIgEAJQgDAIgFAHQgFAHgGAHIgOAKIgQAJIgRAEQgKACgKAAQgKAAgJgCgADHg+QgJAEgHAHQgHAHgDAJQgEALAAAMQAAAKAEAKQAEAJAHAHQAGAIAKADQAJAEAKAAQAMAAAKgEQAJgDAHgIQAGgHAEgKQADgJAAgKQAAgMgEgLQgEgJgHgHQgHgHgJgEQgJgDgLAAQgLAAgJADgAoiBJIAAisIA1gCQAPAAAMADQAKAEAIAFQAHAHADAIQAEAHAAAKQAAANgGAJQgFAKgJAHIAAAAIAJAFQAEADAEAFQADAFACAGQADAHAAAIQAAAOgGAKQgEAKgKAHQgIAHgNACQgMAEgOAAQgjAAgPgCgAn6AkQAFACAIgBQAMAAAGgEQAFgFAAgJQAAgIgFgEQgGgEgKAAIgPAAgAn6g/IAAAhIANAAQAIgBAFgEQAFgEAAgJQAAgHgFgFQgGgDgIAAgAH7BKIAAhsIhNBsIgjAAIAAiuIAoAAIAABsIBNhsIAjAAIAACugAgEBKIAAiuIBnAAIAAAlIhAAAIAAAfIA5AAIAAAlIg5AAIAAAfIBDAAIAAAmgAkYBKIAAhsIhNBsIgjAAIAAiuIAoAAIAABsIBNhsIAjAAIAACug");
	this.shape.setTransform(54.7,10.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ25, new cjs.Rectangle(0,0,109.5,20.8), null);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.samedov();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ24, new cjs.Rectangle(0,0,315,371), null);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.samedov();
	this.instance.parent = this;
	this.instance.setTransform(0,0,1.071,1.071);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ23, new cjs.Rectangle(0,0,337.4,397.4), null);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AlhAaQiTgLAAgPQAAgOCTgLQCTgLDOAAQDQAACSALQCSALAAAOQAAAPiSALQiSALjQgBQjOABiTgLg");
	this.shape.setTransform(50.1,3.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ21, new cjs.Rectangle(0,0,100.1,7.3), null);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.headphone();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.725,0.725);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ20, new cjs.Rectangle(0,0,526.4,195.8), null);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.tv();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.725,0.725);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ19, new cjs.Rectangle(0,0,198.7,134.9), null);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.slayd3();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.725,0.725);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ18, new cjs.Rectangle(0,0,190.7,109.5), null);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.slayd2();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.725,0.725);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(0,0,190.7,109.5), null);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.slayd1();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.725,0.725);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ16, new cjs.Rectangle(0,0,190.7,109.5), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A4FE4Ii6pvMA1/AAAIi6Jvg");
	this.shape.setTransform(153.4,27.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ13, new cjs.Rectangle(-19.4,-3.5,345.7,62.4), null);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AExB5QgNgCgLgEQgLgEgKgHQgKgGgIgIQgJgIgGgKQgHgJgEgMQgFgLgCgNQgDgNAAgOQAAgMACgMQADgMAEgLQAFgLAGgKQAGgKAIgIQAJgJAJgGQAKgHAMgFQALgEANgDQANgCANAAQAOAAAMACQANACALAEQALAFAKAGQAKAGAIAIQAJAIAGAKQAHAKAEALQAFALACANQADANAAANQAAAOgDAMQgCAMgFAMQgEALgHAKQgGAKgJAIQgIAIgKAGQgKAHgLAEQgLAFgNACQgMACgOAAQgNAAgMgCgAEwhCQgNAFgJAKQgJAJgFANQgFAOAAAPQAAAPAFAOQAFANAKAJQAJAKAMAGQANAFANAAQARAAANgFQAMgGAJgKQAIgJAFgOQAEgNAAgPQAAgPgFgOQgFgNgKgJQgJgKgMgFQgMgFgPAAQgOAAgMAFgAAZB6IAAggQgdgCgNgEQgYgLgJgIQgHgGgFgHQgFgHgEgJQgDgIgCgKQgCgKAAgKQAAgLACgKQACgKADgIQAEgJAGgHQAFgHAHgGQAJgIAYgLQAMgEAdgDIAAgZIA1AAIAAAZQAPABAbAGQANAFAUAOQAHAGAGAHQAFAHAEAJQAEAIACAKQACAKAAALQAAAKgCAKQgCAJgEAJQgDAJgGAHQgFAHgHAGIgPALIgSAIQgbAGgQAAIAAAggABOAoQANAAAKgDQAJgDAFgGQAGgFACgIQADgIAAgJQAAgJgCgHQgDgIgFgGQgGgGgJgDQgKgEgNAAgAADgqQgIAEgGAGQgFAFgDAIQgCAIAAAJQAAAJACAIQADAIAGAFQAGAGAIADQAJADAMAAIAAhVQgNAAgJADgALuB3IAAjtICNAAIAAAzIhYAAIAAAmQAKgCARAAQARAAAOAFQAOAFAKAKQAKAJAFANQAGAOAAAQQAAATgGAPQgGAOgMALQgLAKgRAFQgRAGgWAAIhBgCgAMjAVIAAAvIAUACQAQAAAHgHQAGgHAAgLQAAgLgGgHQgHgIgNAAgAlLB3IAAjtICNAAIAAAzIhYAAIAAAmQAKgCARAAQARAAAOAFQAOAFAKAKQAKAJAFANQAGAOAAAQQAAATgGAPQgGAOgMALQgLAKgRAFQgRAGgWAAIhBgCgAkWAVIAAAvIAUACQAQAAAHgHQAGgHAAgLQAAgLgGgHQgHgIgNAAgAtBB3IABg2QAJABAFgCQAIgEAGgNQAHgOAFgbQADgSAGg6IADgwICbAAIAADtIg1AAIAAi6Ig0AAIgFAtQgIA3gFAUQgFAPgFAMQgFALgGAIQgFAHgIAFQgGAFgJADQgHACgKAAgA0iB3IAAjsQAngCAgAAQAUAAAQAEQAPAFAJAIQAKAIAEALQAFAKAAANQAAASgHANQgHANgNAJIAAABQAHACAFAEQAHAEAEAHQAFAHADAIQACAKAAALQAAASgGAPQgHANgMAKQgMAJgQAEQgQAFgTAAQgvAAgVgCgAzsBEQAHACALAAQAPAAAIgHQAIgGAAgNQAAgLgIgFQgHgFgNAAIgVAAgAzshDIAAArIASAAQALAAAGgFQAHgGAAgMQAAgKgIgGQgHgFgLAAgASnB3IAAi6IhGAAIAAgzIDCAAIAAAzIhGAAIAAC6gAO8B3IAAjtICKAAIAAAzIhVAAIAAAqIBMAAIAAAyIhMAAIAAArIBZAAIAAAzgAJ8B3IAAhgIhVAAIAABgIg1AAIAAjtIA1AAIAABbIBVAAIAAhbIA2AAIAADtgAoUB0QgKgDgFgEIATgvQAIAGAIAAQAHAAAEgCQAEgCADgFIADgIIhlipIA9AAIBBB0IAwh0IA2AAIhPC1QgGAOgHAKQgHALgIAHQgIAHgKAEQgKADgMAAQgKAAgLgDgAuLB3IhQhxIAABxIg2AAIAAjtIA2AAIAABoIBMhoIBAAAIhXBuIBeB/g");
	this.shape.setTransform(136,-587.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ12, new cjs.Rectangle(4.5,-600,263,24.6), null);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhhCOICLiNIiNiOIAdgdICpCqIAAAAIABABIioCqg");
	this.shape.setTransform(10,17.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ10, new cjs.Rectangle(0,0,20,34.1), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dacyuk();
	this.instance.parent = this;
	this.instance.setTransform(10,10,0.908,0.908);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ7, new cjs.Rectangle(10,10,205.2,233.4), null);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.smolov();
	this.instance.parent = this;
	this.instance.setTransform(-9,-5,0.936,0.936);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ6, new cjs.Rectangle(-9,-5,247,200.2), null);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dacyuk();
	this.instance.parent = this;
	this.instance.setTransform(0,0,1.066,1.066);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ5, new cjs.Rectangle(0,0,240.9,273.9), null);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.smolov();
	this.instance.parent = this;
	this.instance.setTransform(0,0,1.026,1.026);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ2, new cjs.Rectangle(0,0,270.8,219.5), null);


(lib.Анимация2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.kokorin();
	this.instance.parent = this;
	this.instance.setTransform(-152.5,-150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-152.5,-150,305,300);


(lib.Анимация1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.kokorin();
	this.instance.parent = this;
	this.instance.setTransform(-152.5,-150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-152.5,-150,305,300);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A+mAAIem+mIenemI+neng");
	this.shape.setTransform(195.9,195.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,391.9,391.9), null);


(lib.Символ48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ47();
	this.instance.parent = this;
	this.instance.setTransform(184.2,181.2,1,1,0,0,0,184.2,181.2);
	this.instance.alpha = 0.398;
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ48, new cjs.Rectangle(0,0,368.6,362.5), null);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация1("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(432.5,150);
	this.instance._off = true;

	this.instance_1 = new lib.Анимация2("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(172.5,150);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(399).to({_off:false},0).to({_off:true,x:172.5},19,cjs.Ease.get(-1)).wait(82));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(399).to({_off:false},19,cjs.Ease.get(-1)).to({x:158.9},75,cjs.Ease.get(-1)).to({y:454},6).wait(1));

	// Слой 2
	this.instance_2 = new lib.Символ49();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-1013.9,75.1,1.172,1.172,0,0,0,55.8,11);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(399).to({_off:false},0).to({x:-341.9},19,cjs.Ease.get(-1)).wait(75).to({y:379.1},6).wait(1));

	// Слой 3
	this.instance_3 = new lib.Символ50();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-743.7,112.4,1,1,0,0,0,206,11.2);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(405).to({_off:false},0).to({x:-199.7},19,cjs.Ease.get(-1)).wait(67).to({y:416.4},5).wait(4));

	// Слой 6
	this.instance_4 = new lib.Символ52();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-731.4,113.3,1,1,0,0,0,233,18.4);
	this.instance_4.alpha = 0.801;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(403).to({_off:false},0).to({x:-187.4},19,cjs.Ease.get(-1)).wait(69).to({y:417.3},5).wait(4));

	// Слой 4
	this.instance_5 = new lib.Символ51();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-884.1,150.2,1.065,1.065,0,0,0,62.1,10.4);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(405).to({_off:false},0).to({x:-340.1},19,cjs.Ease.get(-1)).wait(66).to({y:454.2},5).wait(5));

	// Слой 7
	this.instance_6 = new lib.Символ53();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-809.3,172.6,1,1,0,0,0,140.8,6.4);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(407).to({_off:false},0).to({x:-265.3},19,cjs.Ease.get(-1)).wait(63).to({y:476.6},5).wait(6));

	// Слой 1 - копия
	this.instance_7 = new lib.Символ48();
	this.instance_7.parent = this;
	this.instance_7.setTransform(736.2,150.2,1,1,0,0,0,184.2,181.2);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(399).to({_off:false},0).to({x:172.2},19,cjs.Ease.get(-1)).to({x:158.6},75,cjs.Ease.get(-1)).to({y:454.2},6).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ41();
	this.instance.parent = this;
	this.instance.setTransform(153.1,156.5,1,1,0,0,0,153.1,156.5);
	this.instance.alpha = 0.398;
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ40, new cjs.Rectangle(0,0,306.2,313), null);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4
	this.instance = new lib.Символ45();
	this.instance.parent = this;
	this.instance.setTransform(861.5,103.5,1,1,0,0,0,134.5,137.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(299).to({_off:false},0).to({x:549.5},19,cjs.Ease.get(-1)).to({x:538.1},75,cjs.Ease.get(-1)).to({x:536.5,y:878.5},5).wait(102));

	// iphone.png
	this.instance_1 = new lib.Символ38();
	this.instance_1.parent = this;
	this.instance_1.setTransform(70.3,-192.7,1,1,-15,0,0,43.3,65.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(299).to({_off:false},0).to({y:77.7},19).to({regX:43.4,rotation:0,x:70.4},5).wait(70).to({y:682.2},5).wait(102));

	// samsung.png
	this.instance_2 = new lib.Символ39();
	this.instance_2.parent = this;
	this.instance_2.setTransform(37.6,-194.2,1,1,12.8,0,0,42.5,70.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(299).to({_off:false},0).to({y:76.2},19).to({regX:42.4,regY:70.9,rotation:-2.2,x:37.5,y:76.3},5).wait(70).to({rotation:-2.2},0).to({y:835.8},5).wait(102));

	// Слой 6
	this.instance_3 = new lib.Символ43();
	this.instance_3.parent = this;
	this.instance_3.setTransform(97.9,78.6,1,1,0,0,0,138.2,12.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(318).to({_off:false},0).to({x:269.5,alpha:1},5).to({x:270.8},2).to({x:269.5},2).wait(66).to({y:590.1},5).wait(102));

	// Слой 5
	this.instance_4 = new lib.Символ42();
	this.instance_4.parent = this;
	this.instance_4.setTransform(51.1,43.4,1,1,0,0,0,90.4,9.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(318).to({_off:false},0).to({x:222.7,alpha:1},5).to({x:224},2).to({x:222.7},2).wait(66).to({y:539.4},5).wait(102));

	// Слой 7
	this.instance_5 = new lib.Символ44();
	this.instance_5.parent = this;
	this.instance_5.setTransform(90.5,61.7,1,1,0,0,0,182,36.4);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(318).to({_off:false},0).to({x:262.1,alpha:1},5).to({x:263.4},2).to({x:262.1},2).wait(66).to({y:418.2},5).wait(102));

	// Слой 4 - копия
	this.instance_6 = new lib.Символ40();
	this.instance_6.parent = this;
	this.instance_6.setTransform(1077.1,84.5,1,1,0,0,0,153.1,156.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(299).to({_off:false},0).to({x:531.1},19,cjs.Ease.get(-1)).to({x:519.7},75,cjs.Ease.get(-1)).to({x:518.1,y:487.5},5).wait(102));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ31();
	this.instance.parent = this;
	this.instance.setTransform(123,152.2,1,1,0,0,0,123,152.2);
	this.instance.alpha = 0.398;
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ29, new cjs.Rectangle(0,0,245.9,304.6), null);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ36();
	this.instance.parent = this;
	this.instance.setTransform(-359.2,-142.7,1,1,0,0,0,59.8,78.3);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(199).to({_off:false},0).to({y:137.3},19).to({y:139.3},2).to({y:137.3},2).wait(69).to({y:427.3},5).wait(204));

	// Слой 5
	this.instance_1 = new lib.Символ33();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-317.1,121.1,1,1,0,0,0,114.9,9.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(218).to({_off:false},0).to({x:-182.6,alpha:1},5).to({x:-180.6},2).to({x:-182.6},2).wait(65).to({y:421.1},5).wait(203));

	// Слой 4
	this.instance_2 = new lib.Символ32();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-299.9,89.1,1,1,0,0,0,131.8,9.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(218).to({_off:false},0).to({x:-165.4,alpha:1},5).to({x:-163.4},2).to({x:-165.4},2).wait(67).to({y:539.1},5).wait(201));

	// Слой 6
	this.instance_3 = new lib.Символ34();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-341.1,105.5,1,1,0,0,0,169.7,34.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(218).to({_off:false},0).to({x:-162.6,alpha:1},5).to({x:-160.6},2).to({x:-162.6},2).wait(66).to({y:605.5},5).wait(202));

	// Слой 1
	this.instance_4 = new lib.Символ30();
	this.instance_4.parent = this;
	this.instance_4.setTransform(491,169.4,1,1,0,0,0,109,135);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(199).to({_off:false},0).to({x:111},19).to({x:103.4},76,cjs.Ease.get(-1)).to({x:101,y:463.4},5).wait(201));

	// Слой 1 - копия
	this.instance_5 = new lib.Символ29();
	this.instance_5.parent = this;
	this.instance_5.setTransform(458,132.6,1,1,0,0,0,123,152.2);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(199).to({_off:false},0).to({x:78},19).to({x:70.4},75,cjs.Ease.get(-1)).to({x:68,y:862.6},5).wait(202));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ23();
	this.instance.parent = this;
	this.instance.setTransform(168.7,198.7,1,1,0,0,0,168.7,198.7);
	this.instance.alpha = 0.398;
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ22, new cjs.Rectangle(0,0,337.4,397.4), null);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// headphone.png
	this.instance = new lib.Символ20();
	this.instance.parent = this;
	this.instance.setTransform(217.2,79.9,1,1,0,0,0,263.2,97.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(90));

	// tv.png
	this.instance_1 = new lib.Символ19();
	this.instance_1.parent = this;
	this.instance_1.setTransform(188.3,90.4,1,1,0,0,0,99.3,67.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(90));

	// slayd3.jpg
	this.instance_2 = new lib.Символ18();
	this.instance_2.parent = this;
	this.instance_2.setTransform(184.4,77.8,1,1,0,0,0,95.4,54.8);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({alpha:1},29).to({alpha:0},30).wait(31));

	// slayd2.jpg
	this.instance_3 = new lib.Символ17();
	this.instance_3.parent = this;
	this.instance_3.setTransform(184.4,77.8,1,1,0,0,0,95.4,54.8);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(29).to({alpha:1},30).to({alpha:0},30).wait(1));

	// slayd1.jpg
	this.instance_4 = new lib.Символ16();
	this.instance_4.parent = this;
	this.instance_4.setTransform(184.4,77.8,1,1,0,0,0,95.4,54.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:0},29).wait(30).to({alpha:1},30).wait(1));

	// Слой 7
	this.instance_5 = new lib.Символ21();
	this.instance_5.parent = this;
	this.instance_5.setTransform(188.6,157.6,1,1,0,0,0,50.1,3.6);
	this.instance_5.alpha = 0.801;
	this.instance_5.filters = [new cjs.BlurFilter(15, 15, 1)];
	this.instance_5.cache(-2,-2,104,11);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(90));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46,-18,526.4,195.8);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// samedov
	this.instance = new lib.Символ24();
	this.instance.parent = this;
	this.instance.setTransform(163.3,441.7,0.968,0.968,0,0,0,157.5,185.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(100).to({_off:false},0).to({y:193.4},19,cjs.Ease.get(-1)).to({y:191.7},2).to({y:193.4},2).to({x:173.9},71,cjs.Ease.get(-1)).to({x:642.3},5).wait(301));

	// Слой 2
	this.instance_1 = new lib.Символ15();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-96.3,-93.6,1,1,0,0,0,363,135);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(100).to({_off:false},0).to({y:180},19,cjs.Ease.get(-1)).to({y:180.9},2).to({y:180},2).wait(71).to({y:540},5).wait(301));

	// Слой 4
	this.instance_2 = new lib.Символ26();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-274.5,126.4,1,1,0,0,0,134.8,10.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(119).to({_off:false},0).to({x:-22.5,alpha:1},5).to({x:-21.6},2).to({x:-22.5},2).wait(66).to({y:675.4},5).wait(301));

	// Слой 3
	this.instance_3 = new lib.Символ25();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-353.1,89.4,1,1,0,0,0,54.7,10.4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(119).to({_off:false},0).to({x:-101.1,alpha:1},5).to({x:-100.2},2).to({x:-101.1},2).wait(66).to({y:449.4},5).wait(301));

	// Слой 5
	this.instance_4 = new lib.Символ27();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-530.5,106.7,1,1,0,0,0,172.2,37);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(119).to({_off:false},0).wait(5).to({x:-30.5,alpha:0.801},0).wait(70).to({y:565.7},5).wait(301));

	// samedov - копия
	this.instance_5 = new lib.Символ22();
	this.instance_5.parent = this;
	this.instance_5.setTransform(146,671.2,0.968,0.968,0,0,0,168.7,198.7);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(100).to({_off:false},0).to({y:153},19,cjs.Ease.get(-1)).to({y:151.2},2).to({y:153},2).to({regX:168.8,x:156.7},71,cjs.Ease.get(-1)).to({x:520.6},5).wait(301));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4
	this.instance = new lib.Символ10();
	this.instance.parent = this;
	this.instance.setTransform(172.4,28.9,0.533,0.533,0,0,0,10.1,17.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:10.2,regY:17.2,scaleX:0.53,scaleY:0.53,x:175.5},6,cjs.Ease.get(-1)).to({regX:10.1,regY:17.1,scaleX:0.53,scaleY:0.53,x:179.4},8,cjs.Ease.get(1)).to({regX:10.2,regY:17.2,scaleX:0.53,scaleY:0.53,x:176.2},7,cjs.Ease.get(-1)).to({regX:10.1,regY:17.1,scaleX:0.53,scaleY:0.53,x:172.4},8,cjs.Ease.get(1)).wait(1));

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmnBWQgJgBgJgDIgPgIQgHgEgGgGQgGgGgEgHQgFgHgDgIQgEgIgBgJQgCgJAAgKQAAgIACgJIAEgQQADgJAEgHQAEgHAGgGQAFgGAIgEQAGgFAJgDQAIgEAKgCQAKgBAKAAQAMAAATAFQAOAEAIAIIgRAdIgQgHQgJgDgLAAQgKAAgIAEQgJADgGAGQgHAHgEAJQgDALAAALQAAALADAJQAEAKAHAHQAHAHAJADQAKAFALAAQAKAAAJgDQAKgEAJgGIAOAdQgDAEgHAEIgNAHQgVAFgLAAQgKAAgJgCgAp3BUIAAioQAcgCAXAAQAPAAAMAEQAKADAHAGQAHAGAEAIQADAHAAAJQAAANgFAJQgFAKgKAGIAAAAIAJAFQAFADADAEQADAGACAGQADAGAAAIQAAAOgFAKQgFAKgJAGQgJAHgLADQgNADgOAAQghAAgPgCgApQAwQAFACAIAAQALAAAGgFQAGgFAAgJQAAgHgGgEQgFgEgKAAIgPAAgApQgwIAAAfIAMAAQAJAAAEgEQAGgEAAgIQAAgIgGgEQgFgEgIAAgAIBBVIAAipIAnAAIAAA1IAQgBQAQAAAMAEQAMAEAIAIQAIAHAEAKQAEAKAAANQAAAOgFALQgFAMgJAIQgNAJgJADQgUAFgMAAgAIoAFIAAArIAMABQAGAAAFgBQAFgBAEgDQADgDACgFQACgEAAgHQAAgGgDgEQgBgEgEgDQgHgFgMAAgAGPBVIAAiFIgzAAIAAgkICNAAIAAAkIgzAAIAACFgAEdBVIAAhpIhMBpIgiAAIAAipIAnAAIAABoIBLhoIAjAAIAACpgABcBVIAAiFIg7AAIAACFIgmAAIAAipICIAAIAACpgAiYBTIgLgFIAOgiQAGAFAGAAQAFAAADgCQADgCACgDIACgGIhJh4IArAAIAxBTIAihTIAnAAIg5CBQgEAKgFAHQgGAIgFAFQgGAFgHADQgIACgJAAQgHAAgIgCgAkiBVIAAiFIgzAAIAAgkICNAAIAAAkIgzAAIAACFg");
	this.shape.setTransform(84.9,28.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(30));

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D6271F").s().p("AvJETQgyAAAAgyIAAnBQAAgyAyAAIeTAAQAyAAAAAyIAAHBQAAAygyAAg");
	this.shape_1.setTransform(102,27.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(30));

	// Слой 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#9E1A14").s().p("AvJETQgyAAAAgyIAAnBQAAgyAyAAIeTAAQAyAAAAAyIAAHBQAAAygyAAg");
	this.shape_2.setTransform(102,31.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,204,59.1);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ55();
	this.instance.parent = this;
	this.instance.setTransform(140.2,29.6,1,1,0,0,0,131.8,20.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.699},9).to({alpha:1},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(8.4,9.5,263.5,40.2);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ5();
	this.instance.parent = this;
	this.instance.setTransform(149.3,148.7,1,1,0,0,0,133.2,148.7);
	this.instance.alpha = 0.398;
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ4, new cjs.Rectangle(16.1,0,240.9,273.9), null);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.parent = this;
	this.instance.setTransform(264.1,128.2,1,1,0,0,0,264.1,128.2);
	this.instance.alpha = 0.398;
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ3, new cjs.Rectangle(0,0,270.8,219.5), null);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// smolov.png
	this.instance = new lib.Символ6();
	this.instance.parent = this;
	this.instance.setTransform(-231.4,209.5,1,1,0,0,0,225.6,109.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:38.6},19,cjs.Ease.get(1)).to({x:45.6},68).to({x:45.8},2).wait(5).to({y:461.5},5,cjs.Ease.get(-1)).wait(401));

	// smolov.png - копия
	this.instance_1 = new lib.Символ3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-212.9,182.2,1,1,0,0,0,264.1,128.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:57.1},24,cjs.Ease.get(1)).to({x:64.3},65).wait(5).to({y:434.2},5,cjs.Ease.get(-1)).wait(401));

	// vstupayte
	this.instance_2 = new lib.Символ8();
	this.instance_2.parent = this;
	this.instance_2.setTransform(194.4,-92.4,1,1,0,0,0,137.2,35.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:100.2},19).to({y:103.8},2).to({y:100.2},2).wait(69).to({y:658.2},5,cjs.Ease.get(-1)).wait(403));

	// Слой 5
	this.instance_3 = new lib.Символ13();
	this.instance_3.parent = this;
	this.instance_3.setTransform(194.9,-97.6,1,1,0,0,0,153.3,27.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:95},19).to({y:98.6},2).to({y:95},2).wait(69).to({y:707},5,cjs.Ease.get(-1)).wait(403));

	// club
	this.instance_4 = new lib.Символ12();
	this.instance_4.parent = this;
	this.instance_4.setTransform(195.5,366.2,1,1,0,0,0,134.7,26.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({y:782.9},19).to({y:784.7},2).to({y:782.9},2).wait(69).to({y:173.6},0).to({y:569.6},5,cjs.Ease.get(-1)).wait(403));

	// dacyuk.png
	this.instance_5 = new lib.Символ7();
	this.instance_5.parent = this;
	this.instance_5.setTransform(748.5,161.7,1,1,0,0,0,113.5,126.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({x:487.5},19,cjs.Ease.get(1)).to({x:480.3},70).wait(3).to({y:437.1},5,cjs.Ease.get(-1)).wait(403));

	// dacyuk.png - копия
	this.instance_6 = new lib.Символ4();
	this.instance_6.parent = this;
	this.instance_6.setTransform(729.2,144.7,1,1,0,0,0,133.2,148.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({x:468.2},24,cjs.Ease.get(1)).to({x:461},65).wait(3).to({y:420.1},5,cjs.Ease.get(-1)).wait(403));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-477,-260.4,1330,555.7);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Symbol 2
	this.instance = new lib.Symbol2();
	this.instance.parent = this;
	this.instance.setTransform(1605,885.9,0.546,0.754,0,0,0,196,196.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.5},14).to({alpha:1},15).wait(1));

	// Symbol 2
	this.instance_1 = new lib.Symbol2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(1498.1,738.3,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_1.alpha = 0.93;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:196,regY:196,x:1498,y:738.2,alpha:0.5},12).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,y:738.3,alpha:0.961},1).wait(1));

	// Symbol 2
	this.instance_2 = new lib.Symbol2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(1498.1,1033.4,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_2.alpha = 0.609;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:196,regY:196,x:1498,y:1033.3,alpha:0.5},3).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,y:1033.4,alpha:0.641},10).wait(1));

	// Symbol 2
	this.instance_3 = new lib.Symbol2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(1391.1,885.8,0.546,0.754,0,0,0,196.2,196.2);
	this.instance_3.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({regX:196,regY:196.1,x:1391,alpha:1},12).wait(1).to({alpha:0.5},14).to({regX:196.1,y:885.7,alpha:0.57},2).wait(1));

	// Symbol 2
	this.instance_4 = new lib.Symbol2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(1177.1,885.9,0.546,0.754,0,0,0,196.2,196.2);
	this.instance_4.alpha = 0.891;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({regX:196,regY:196.1,x:1177,alpha:0.5},11).to({alpha:1},15).wait(1).to({regX:196.1,x:1177.1,alpha:0.93},2).wait(1));

	// Symbol 2
	this.instance_5 = new lib.Symbol2();
	this.instance_5.parent = this;
	this.instance_5.setTransform(1070.1,738.3,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_5.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({regX:196,regY:196,x:1070,y:738.2,alpha:1},6).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,x:1070.1,y:738.3,alpha:0.77},8).wait(1));

	// Symbol 2
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(1070,1033.3,0.546,0.754,0,0,0,196,196);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({alpha:0.5},14).to({alpha:1},15).wait(1));

	// Symbol 2
	this.instance_7 = new lib.Symbol2();
	this.instance_7.parent = this;
	this.instance_7.setTransform(963.1,885.8,0.546,0.754,0,0,0,196.2,196.2);
	this.instance_7.alpha = 0.68;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({regX:196,regY:196.1,x:963,alpha:0.5},5).to({alpha:1},15).wait(1).to({regX:196.1,y:885.7,alpha:0.711},8).wait(1));

	// Symbol 2
	this.instance_8 = new lib.Symbol2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(749.1,885.9,0.546,0.754,0,0,0,196.2,196.2);
	this.instance_8.alpha = 0.93;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({regX:196,regY:196.1,alpha:1},2).wait(1).to({alpha:0.5},14).to({regX:196.1,alpha:0.898},12).wait(1));

	// Symbol 2
	this.instance_9 = new lib.Symbol2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(642.1,738.3,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_9.alpha = 0.82;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({regX:196,regY:196,x:642,y:738.2,alpha:0.5},9).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,x:642.1,y:738.3,alpha:0.859},4).wait(1));

	// Symbol 2
	this.instance_10 = new lib.Symbol2();
	this.instance_10.parent = this;
	this.instance_10.setTransform(642.1,1033.4,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_10.alpha = 0.73;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({regX:196,regY:196,x:642,y:1033.3,alpha:1},8).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,x:642.1,y:1033.4,alpha:0.699},6).wait(1));

	// Symbol 2
	this.instance_11 = new lib.Symbol2();
	this.instance_11.parent = this;
	this.instance_11.setTransform(535,885.8,0.546,0.754,0,0,0,196,196.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({alpha:0.5},14).to({alpha:1},15).wait(1));

	// Symbol 2
	this.instance_12 = new lib.Symbol2();
	this.instance_12.parent = this;
	this.instance_12.setTransform(321.1,885.9,0.546,0.754,0,0,0,196.2,196.2);
	this.instance_12.alpha = 0.609;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({regX:196,regY:196.1,alpha:0.5},3).to({alpha:1},15).wait(1).to({regX:196.1,alpha:0.641},10).wait(1));

	// Symbol 2
	this.instance_13 = new lib.Symbol2();
	this.instance_13.parent = this;
	this.instance_13.setTransform(214.1,738.3,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_13.alpha = 0.871;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({regX:196,regY:196,x:214,y:738.2,alpha:1},4).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,y:738.3,alpha:0.828},10).wait(1));

	// Symbol 2
	this.instance_14 = new lib.Symbol2();
	this.instance_14.parent = this;
	this.instance_14.setTransform(214.1,1033.4,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_14.alpha = 0.82;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({regX:196,regY:196,x:214,y:1033.3,alpha:0.5},9).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,y:1033.4,alpha:0.859},4).wait(1));

	// Symbol 2
	this.instance_15 = new lib.Symbol2();
	this.instance_15.parent = this;
	this.instance_15.setTransform(107.1,885.8,0.546,0.754,0,0,0,196,196.2);
	this.instance_15.alpha = 0.57;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({regY:196.1,x:107,alpha:0.5},2).to({alpha:1},15).wait(1).to({y:885.7,alpha:0.609},11).wait(1));

	// Symbol 2
	this.instance_16 = new lib.Symbol2();
	this.instance_16.parent = this;
	this.instance_16.setTransform(1819.1,1181,0.546,0.754,0,0,0,196,196.1);
	this.instance_16.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({regY:196,alpha:1},12).wait(1).to({alpha:0.5},14).to({regY:196.1,alpha:0.57},2).wait(1));

	// Symbol 2
	this.instance_17 = new lib.Symbol2();
	this.instance_17.parent = this;
	this.instance_17.setTransform(1712.1,1033.3,0.546,0.754,0,0,0,196,196);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(1).to({alpha:0.5},14).to({regY:196.1,y:1033.4,alpha:0.961},14).wait(1));

	// Symbol 2
	this.instance_18 = new lib.Symbol2();
	this.instance_18.parent = this;
	this.instance_18.setTransform(1712.1,1328.6,0.546,0.754,0,0,0,196,196.1);
	this.instance_18.alpha = 0.77;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).to({regY:196,y:1328.5,alpha:1},7).wait(1).to({alpha:0.5},14).to({regY:196.1,y:1328.6,alpha:0.73},7).wait(1));

	// Symbol 2
	this.instance_19 = new lib.Symbol2();
	this.instance_19.parent = this;
	this.instance_19.setTransform(1605.1,1181,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_19.alpha = 0.641;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).to({regX:196,regY:196,x:1605,y:1180.9,alpha:0.5},4).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,x:1605.1,y:1181,alpha:0.68},9).wait(1));

	// Symbol 2
	this.instance_20 = new lib.Symbol2();
	this.instance_20.parent = this;
	this.instance_20.setTransform(1391.2,1181,0.546,0.754,0,0,0,196.3,196.1);
	this.instance_20.alpha = 0.699;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).to({regX:196.1,regY:196,x:1391.1,alpha:1},9).wait(1).to({alpha:0.5},14).to({regX:196.2,regY:196.1,x:1391.2,alpha:0.672},5).wait(1));

	// Symbol 2
	this.instance_21 = new lib.Symbol2();
	this.instance_21.parent = this;
	this.instance_21.setTransform(1284.1,1033.4,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_21.alpha = 0.871;

	this.timeline.addTween(cjs.Tween.get(this.instance_21).to({regX:196,regY:196,y:1033.3,alpha:1},4).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,y:1033.4,alpha:0.828},10).wait(1));

	// Symbol 2
	this.instance_22 = new lib.Symbol2();
	this.instance_22.parent = this;
	this.instance_22.setTransform(1284.1,1328.6,0.546,0.754,0,0,0,196.1,196.1);
	this.instance_22.alpha = 0.969;

	this.timeline.addTween(cjs.Tween.get(this.instance_22).to({regX:196,regY:196,y:1328.5,alpha:1},1).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,y:1328.6,alpha:0.93},13).wait(1));

	// Symbol 2
	this.instance_23 = new lib.Symbol2();
	this.instance_23.parent = this;
	this.instance_23.setTransform(1177.1,1181,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_23.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance_23).to({regX:196,regY:196,x:1177,y:1180.9,alpha:1},6).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,x:1177.1,y:1181,alpha:0.77},8).wait(1));

	// Symbol 2
	this.instance_24 = new lib.Symbol2();
	this.instance_24.parent = this;
	this.instance_24.setTransform(963.1,1181,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_24.alpha = 0.68;

	this.timeline.addTween(cjs.Tween.get(this.instance_24).to({regX:196,regY:196,alpha:0.5},5).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,alpha:0.711},8).wait(1));

	// Symbol 2
	this.instance_25 = new lib.Symbol2();
	this.instance_25.parent = this;
	this.instance_25.setTransform(856.1,1033.4,0.546,0.754,0,0,0,196.1,196.1);
	this.instance_25.alpha = 0.539;

	this.timeline.addTween(cjs.Tween.get(this.instance_25).to({regX:196,regY:196,y:1033.3,alpha:1},14).wait(1).to({alpha:0.5},14).wait(1));

	// Symbol 2
	this.instance_26 = new lib.Symbol2();
	this.instance_26.parent = this;
	this.instance_26.setTransform(856.1,1328.6,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_26.alpha = 0.859;

	this.timeline.addTween(cjs.Tween.get(this.instance_26).to({regX:196,regY:196,y:1328.5,alpha:0.5},10).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,y:1328.6,alpha:0.891},3).wait(1));

	// Symbol 2
	this.instance_27 = new lib.Symbol2();
	this.instance_27.parent = this;
	this.instance_27.setTransform(749.1,1181,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_27.alpha = 0.891;

	this.timeline.addTween(cjs.Tween.get(this.instance_27).to({regX:196,regY:196,y:1180.9,alpha:0.5},11).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,y:1181,alpha:0.93},2).wait(1));

	// Symbol 2
	this.instance_28 = new lib.Symbol2();
	this.instance_28.parent = this;
	this.instance_28.setTransform(535.2,1181,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_28.alpha = 0.699;

	this.timeline.addTween(cjs.Tween.get(this.instance_28).to({regX:196,regY:196,x:535.1,alpha:1},9).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,x:535.2,alpha:0.672},5).wait(1));

	// Symbol 2
	this.instance_29 = new lib.Symbol2();
	this.instance_29.parent = this;
	this.instance_29.setTransform(428.2,1033.4,0.546,0.754,0,0,0,196.3,196.1);
	this.instance_29.alpha = 0.93;

	this.timeline.addTween(cjs.Tween.get(this.instance_29).to({regX:196.1,regY:196,x:428.1,y:1033.3,alpha:1},2).wait(1).to({alpha:0.5},14).to({regX:196.2,regY:196.1,x:428.2,y:1033.4,alpha:0.898},12).wait(1));

	// Symbol 2
	this.instance_30 = new lib.Symbol2();
	this.instance_30.parent = this;
	this.instance_30.setTransform(428.2,1328.6,0.546,0.754,0,0,0,196.3,196.1);
	this.instance_30.alpha = 0.57;

	this.timeline.addTween(cjs.Tween.get(this.instance_30).to({regX:196.1,regY:196,x:428.1,y:1328.5,alpha:0.5},2).to({alpha:1},15).wait(1).to({regX:196.2,regY:196.1,x:428.2,y:1328.6,alpha:0.609},11).wait(1));

	// Symbol 2
	this.instance_31 = new lib.Symbol2();
	this.instance_31.parent = this;
	this.instance_31.setTransform(321.1,1181,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_31.alpha = 0.629;

	this.timeline.addTween(cjs.Tween.get(this.instance_31).to({regX:196,regY:196,y:1180.9,alpha:1},11).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,y:1181,alpha:0.602},3).wait(1));

	// Symbol 2
	this.instance_32 = new lib.Symbol2();
	this.instance_32.parent = this;
	this.instance_32.setTransform(1605.1,295.3,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_32.alpha = 0.93;

	this.timeline.addTween(cjs.Tween.get(this.instance_32).to({regX:196,regY:196,x:1605,alpha:1},2).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,x:1605.1,y:295.4,alpha:0.898},12).wait(1));

	// Symbol 2
	this.instance_33 = new lib.Symbol2();
	this.instance_33.parent = this;
	this.instance_33.setTransform(1498,147.7,0.546,0.754,0,0,0,196,195.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_33).to({alpha:0.5},14).to({alpha:1},15).wait(1));

	// Symbol 2
	this.instance_34 = new lib.Symbol2();
	this.instance_34.parent = this;
	this.instance_34.setTransform(1498.1,442.8,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_34.alpha = 0.75;

	this.timeline.addTween(cjs.Tween.get(this.instance_34).to({regX:196,regY:196,x:1498,alpha:0.5},7).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,y:442.9,alpha:0.789},6).wait(1));

	// Symbol 2
	this.instance_35 = new lib.Symbol2();
	this.instance_35.parent = this;
	this.instance_35.setTransform(1391.1,295.2,0.546,0.754,0,0,0,196.2,196.2);
	this.instance_35.alpha = 0.629;

	this.timeline.addTween(cjs.Tween.get(this.instance_35).to({regX:196,regY:196.1,x:1391,y:295.3,alpha:1},11).wait(1).to({alpha:0.5},14).to({regX:196.1,y:295.2,alpha:0.602},3).wait(1));

	// Symbol 2
	this.instance_36 = new lib.Symbol2();
	this.instance_36.parent = this;
	this.instance_36.setTransform(1177.1,295.3,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_36.alpha = 0.84;

	this.timeline.addTween(cjs.Tween.get(this.instance_36).to({regX:196,regY:196,x:1177,alpha:1},5).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,x:1177.1,y:295.4,alpha:0.801},9).wait(1));

	// Symbol 2
	this.instance_37 = new lib.Symbol2();
	this.instance_37.parent = this;
	this.instance_37.setTransform(1070.1,147.7,0.546,0.754,0,0,0,196.2,196);
	this.instance_37.alpha = 0.57;

	this.timeline.addTween(cjs.Tween.get(this.instance_37).to({regX:196,regY:195.9,x:1070,alpha:0.5},2).to({alpha:1},15).wait(1).to({regX:196.1,x:1070.1,alpha:0.609},11).wait(1));

	// Symbol 2
	this.instance_38 = new lib.Symbol2();
	this.instance_38.parent = this;
	this.instance_38.setTransform(1070,442.8,0.546,0.754,0,0,0,196,196);

	this.timeline.addTween(cjs.Tween.get(this.instance_38).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,x:1070.1,y:442.9,alpha:0.961},14).wait(1));

	// Symbol 2
	this.instance_39 = new lib.Symbol2();
	this.instance_39.parent = this;
	this.instance_39.setTransform(963.1,295.2,0.546,0.754,0,0,0,196.2,196.2);
	this.instance_39.alpha = 0.699;

	this.timeline.addTween(cjs.Tween.get(this.instance_39).to({regX:196,regY:196.1,x:963,y:295.3,alpha:1},9).wait(1).to({alpha:0.5},14).to({regX:196.1,y:295.2,alpha:0.672},5).wait(1));

	// Symbol 2
	this.instance_40 = new lib.Symbol2();
	this.instance_40.parent = this;
	this.instance_40.setTransform(749.1,295.3,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_40.alpha = 0.898;

	this.timeline.addTween(cjs.Tween.get(this.instance_40).to({regX:196,regY:196,alpha:1},3).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,y:295.4,alpha:0.871},11).wait(1));

	// Symbol 2
	this.instance_41 = new lib.Symbol2();
	this.instance_41.parent = this;
	this.instance_41.setTransform(642.1,147.7,0.546,0.754,0,0,0,196.2,196);
	this.instance_41.alpha = 0.68;

	this.timeline.addTween(cjs.Tween.get(this.instance_41).to({regX:196,regY:195.9,x:642,alpha:0.5},5).to({alpha:1},15).wait(1).to({regX:196.1,x:642.1,alpha:0.711},8).wait(1));

	// Symbol 2
	this.instance_42 = new lib.Symbol2();
	this.instance_42.parent = this;
	this.instance_42.setTransform(642.1,442.8,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_42.alpha = 0.891;

	this.timeline.addTween(cjs.Tween.get(this.instance_42).to({regX:196,regY:196,x:642,alpha:0.5},11).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,x:642.1,y:442.9,alpha:0.93},2).wait(1));

	// Symbol 2
	this.instance_43 = new lib.Symbol2();
	this.instance_43.parent = this;
	this.instance_43.setTransform(535,295.2,0.546,0.754,0,0,0,196.1,196.1);
	this.instance_43.alpha = 0.539;

	this.timeline.addTween(cjs.Tween.get(this.instance_43).to({regX:196,y:295.3,alpha:1},14).wait(1).to({alpha:0.5},14).wait(1));

	// Symbol 2
	this.instance_44 = new lib.Symbol2();
	this.instance_44.parent = this;
	this.instance_44.setTransform(321.1,295.3,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_44.alpha = 0.77;

	this.timeline.addTween(cjs.Tween.get(this.instance_44).to({regX:196,regY:196,alpha:1},7).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,y:295.4,alpha:0.73},7).wait(1));

	// Symbol 2
	this.instance_45 = new lib.Symbol2();
	this.instance_45.parent = this;
	this.instance_45.setTransform(214.1,147.7,0.546,0.754,0,0,0,196.2,196);
	this.instance_45.alpha = 0.898;

	this.timeline.addTween(cjs.Tween.get(this.instance_45).to({regX:196,regY:195.9,x:214,alpha:1},3).wait(1).to({alpha:0.5},14).to({regX:196.1,alpha:0.871},11).wait(1));

	// Symbol 2
	this.instance_46 = new lib.Symbol2();
	this.instance_46.parent = this;
	this.instance_46.setTransform(214.1,442.8,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_46.alpha = 0.789;

	this.timeline.addTween(cjs.Tween.get(this.instance_46).to({regX:196,regY:196,x:214,alpha:0.5},8).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,y:442.9,alpha:0.82},5).wait(1));

	// Symbol 2
	this.instance_47 = new lib.Symbol2();
	this.instance_47.parent = this;
	this.instance_47.setTransform(107.1,295.2,0.546,0.754,0,0,0,196,196.2);
	this.instance_47.alpha = 0.609;

	this.timeline.addTween(cjs.Tween.get(this.instance_47).to({regY:196.1,x:107,y:295.3,alpha:0.5},3).to({alpha:1},15).wait(1).to({y:295.2,alpha:0.641},10).wait(1));

	// Symbol 2
	this.instance_48 = new lib.Symbol2();
	this.instance_48.parent = this;
	this.instance_48.setTransform(1819.1,590.5,0.546,0.754,0,0,0,196,196.1);
	this.instance_48.alpha = 0.672;

	this.timeline.addTween(cjs.Tween.get(this.instance_48).to({regY:196,alpha:1},10).wait(1).to({alpha:0.5},14).to({regY:196.1,alpha:0.629},4).wait(1));

	// Symbol 2
	this.instance_49 = new lib.Symbol2();
	this.instance_49.parent = this;
	this.instance_49.setTransform(1712.1,442.8,0.546,0.754,0,0,0,196,196.1);
	this.instance_49.alpha = 0.871;

	this.timeline.addTween(cjs.Tween.get(this.instance_49).to({regY:196,alpha:1},4).wait(1).to({alpha:0.5},14).to({regY:196.1,y:442.9,alpha:0.828},10).wait(1));

	// Symbol 2
	this.instance_50 = new lib.Symbol2();
	this.instance_50.parent = this;
	this.instance_50.setTransform(1712.1,738.1,0.546,0.754,0,0,0,196,196.1);
	this.instance_50.alpha = 0.859;

	this.timeline.addTween(cjs.Tween.get(this.instance_50).to({regY:196,y:738,alpha:0.5},10).to({alpha:1},15).wait(1).to({regY:196.1,y:738.1,alpha:0.891},3).wait(1));

	// Symbol 2
	this.instance_51 = new lib.Symbol2();
	this.instance_51.parent = this;
	this.instance_51.setTransform(1605.1,590.4,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_51.alpha = 0.898;

	this.timeline.addTween(cjs.Tween.get(this.instance_51).to({regX:196,regY:196,x:1605,alpha:1},3).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,x:1605.1,y:590.5,alpha:0.871},11).wait(1));

	// Symbol 2
	this.instance_52 = new lib.Symbol2();
	this.instance_52.parent = this;
	this.instance_52.setTransform(1391.2,590.5,0.546,0.754,0,0,0,196.3,196.1);
	this.instance_52.alpha = 0.57;

	this.timeline.addTween(cjs.Tween.get(this.instance_52).to({regX:196.1,regY:196,x:1391.1,alpha:0.5},2).to({alpha:1},15).wait(1).to({regX:196.2,regY:196.1,x:1391.2,alpha:0.609},11).wait(1));

	// Symbol 2
	this.instance_53 = new lib.Symbol2();
	this.instance_53.parent = this;
	this.instance_53.setTransform(1284.1,442.8,0.546,0.754,0,0,0,196,196);

	this.timeline.addTween(cjs.Tween.get(this.instance_53).to({alpha:0.5},14).to({alpha:1},15).wait(1));

	// Symbol 2
	this.instance_54 = new lib.Symbol2();
	this.instance_54.parent = this;
	this.instance_54.setTransform(1284.1,738.1,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_54.alpha = 0.629;

	this.timeline.addTween(cjs.Tween.get(this.instance_54).to({regX:196,regY:196,y:738,alpha:1},11).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,y:738.1,alpha:0.602},3).wait(1));

	// Symbol 2
	this.instance_55 = new lib.Symbol2();
	this.instance_55.parent = this;
	this.instance_55.setTransform(1177.1,590.4,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_55.alpha = 0.93;

	this.timeline.addTween(cjs.Tween.get(this.instance_55).to({regX:196,regY:196,x:1177,alpha:1},2).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,x:1177.1,y:590.5,alpha:0.898},12).wait(1));

	// Symbol 2
	this.instance_56 = new lib.Symbol2();
	this.instance_56.parent = this;
	this.instance_56.setTransform(963.1,590.5,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_56.alpha = 0.789;

	this.timeline.addTween(cjs.Tween.get(this.instance_56).to({regX:196,regY:196,alpha:0.5},8).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,alpha:0.82},5).wait(1));

	// Symbol 2
	this.instance_57 = new lib.Symbol2();
	this.instance_57.parent = this;
	this.instance_57.setTransform(856.1,442.8,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_57.alpha = 0.871;

	this.timeline.addTween(cjs.Tween.get(this.instance_57).to({regX:196,regY:196,alpha:1},4).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,y:442.9,alpha:0.828},10).wait(1));

	// Symbol 2
	this.instance_58 = new lib.Symbol2();
	this.instance_58.parent = this;
	this.instance_58.setTransform(856.1,738.1,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_58.alpha = 0.672;

	this.timeline.addTween(cjs.Tween.get(this.instance_58).to({regX:196,regY:196,y:738,alpha:1},10).wait(1).to({alpha:0.5},14).to({regX:196.1,regY:196.1,y:738.1,alpha:0.629},4).wait(1));

	// Symbol 2
	this.instance_59 = new lib.Symbol2();
	this.instance_59.parent = this;
	this.instance_59.setTransform(749.1,590.4,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_59.alpha = 0.57;

	this.timeline.addTween(cjs.Tween.get(this.instance_59).to({regX:196,regY:196,alpha:0.5},2).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,y:590.5,alpha:0.609},11).wait(1));

	// Symbol 2
	this.instance_60 = new lib.Symbol2();
	this.instance_60.parent = this;
	this.instance_60.setTransform(535.2,590.5,0.546,0.754,0,0,0,196.2,196.1);
	this.instance_60.alpha = 0.789;

	this.timeline.addTween(cjs.Tween.get(this.instance_60).to({regX:196,regY:196,x:535.1,alpha:0.5},8).to({alpha:1},15).wait(1).to({regX:196.1,regY:196.1,x:535.2,alpha:0.82},5).wait(1));

	// Symbol 2
	this.instance_61 = new lib.Symbol2();
	this.instance_61.parent = this;
	this.instance_61.setTransform(428.2,442.8,0.546,0.754,0,0,0,196.3,196.1);
	this.instance_61.alpha = 0.93;

	this.timeline.addTween(cjs.Tween.get(this.instance_61).to({regX:196.1,regY:196,x:428.1,alpha:0.5},12).to({alpha:1},15).wait(1).to({regX:196.2,regY:196.1,x:428.2,y:442.9,alpha:0.961},1).wait(1));

	// Symbol 2
	this.instance_62 = new lib.Symbol2();
	this.instance_62.parent = this;
	this.instance_62.setTransform(428.2,738.1,0.546,0.754,0,0,0,196.3,196.1);
	this.instance_62.alpha = 0.73;

	this.timeline.addTween(cjs.Tween.get(this.instance_62).to({regX:196.1,regY:196,x:428.1,y:738,alpha:1},8).wait(1).to({alpha:0.5},14).to({regX:196.2,regY:196.1,x:428.2,y:738.1,alpha:0.699},6).wait(1));

	// Symbol 2
	this.instance_63 = new lib.Symbol2();
	this.instance_63.parent = this;
	this.instance_63.setTransform(321.1,590.4,0.546,0.754,0,0,0,196,196);

	this.timeline.addTween(cjs.Tween.get(this.instance_63).to({alpha:0.5},14).to({alpha:1},15).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,1925.9,1476.1);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Symbol3();
	this.instance.parent = this;
	this.instance.setTransform(354.1,166.9,0.392,0.284,0,1,-1,962.2,737.9);
	this.instance.alpha = 0.078;
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.bg();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ35, new cjs.Rectangle(-24.7,-47,774.7,427.8), null);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ9();
	this.instance.parent = this;
	this.instance.setTransform(102,27.5,1,1,0,0,0,102,27.5);

	this.instance_1 = new lib.Символ10();
	this.instance_1.parent = this;
	this.instance_1.setTransform(172.4,29.6,0.533,0.533,0,0,0,10.1,17.1);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmnBWQgJgBgJgDIgPgIQgHgEgGgGQgGgGgEgHQgFgHgDgIQgEgIgBgJQgCgJAAgKQAAgIACgJIAEgQQADgJAEgHQAEgHAGgGQAFgGAIgEQAGgFAJgDQAIgEAKgCQAKgBAKAAQAMAAATAFQAOAEAIAIIgRAdIgQgHQgJgDgLAAQgKAAgIAEQgJADgGAGQgHAHgEAJQgDALAAALQAAALADAJQAEAKAHAHQAHAHAJADQAKAFALAAQAKAAAJgDQAKgEAJgGIAOAdQgDAEgHAEIgNAHQgVAFgLAAQgKAAgJgCgAp3BUIAAioQAcgCAXAAQAPAAAMAEQAKADAHAGQAHAGAEAIQADAHAAAJQAAANgFAJQgFAKgKAGIAAAAIAJAFQAFADADAEQADAGACAGQADAGAAAIQAAAOgFAKQgFAKgJAGQgJAHgLADQgNADgOAAQghAAgPgCgApQAwQAFACAIAAQALAAAGgFQAGgFAAgJQAAgHgGgEQgFgEgKAAIgPAAgApQgwIAAAfIAMAAQAJAAAEgEQAGgEAAgIQAAgIgGgEQgFgEgIAAgAIBBVIAAipIAnAAIAAA1IAQgBQAQAAAMAEQAMAEAIAIQAIAHAEAKQAEAKAAANQAAAOgFALQgFAMgJAIQgNAJgJADQgUAFgMAAgAIoAFIAAArIAMABQAGAAAFgBQAFgBAEgDQADgDACgFQACgEAAgHQAAgGgDgEQgBgEgEgDQgHgFgMAAgAGPBVIAAiFIgzAAIAAgkICNAAIAAAkIgzAAIAACFgAEdBVIAAhpIhMBpIgiAAIAAipIAnAAIAABoIBLhoIAjAAIAACpgABcBVIAAiFIg7AAIAACFIgmAAIAAipICIAAIAACpgAiYBTIgLgFIAOgiQAGAFAGAAQAFAAADgCQADgCACgDIACgGIhJh4IArAAIAxBTIAihTIAnAAIg5CBQgEAKgFAHQgGAIgFAFQgGAFgHADQgIACgJAAQgHAAgIgCgAkiBVIAAiFIgzAAIAAgkICNAAIAAAkIgzAAIAACFg");
	this.shape.setTransform(84.9,29.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#9E1A14").s().p("AvJAoQgyAAAAgxIAAgeQABAuAxAAIeTAAQAxAAABguIAAAeQAAAxgyAAg");
	this.shape_1.setTransform(102,55);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D6271F").s().p("AvJETQgxAAgBgvIAAnEQAAgyAyAAIeTAAQAyAAAAAyIAAHEQgBAvgxAAgApUhNQgKACgJADQgIADgGAFQgIAEgGAHQgFAGgEAHQgFAHgDAIIgEARQgBAIAAAIQAAAKACAJQABAJAEAIQADAJAEAGQAFAIAGAFQAGAGAHAFIAPAHQAJAEAJABQAJACAKAAQALAAAVgGIANgHQAHgDADgFIgPgdQgIAHgKADQgKADgJAAQgLAAgKgEQgJgEgHgHQgHgGgEgKQgEgKAAgLQAAgLAEgKQAEgJAHgHQAGgHAJgDQAIgDAKAAQALAAAJADIAQAHIARgdQgIgIgOgFQgUgFgLAAQgLAAgJACgAsihLIAACoQAPACAhAAQAOAAANgEQALgDAIgHQAJgGAGgJQAEgLAAgNQABgIgDgHQgCgGgEgFQgDgFgEgDIgJgFIAAgBQAKgFAEgJQAFgJABgOQAAgJgEgHQgEgIgGgFQgIgGgKgEQgLgDgPAAQgXAAgcACgAFWBeIAuAAQAMAAATgEQAJgDAOgKQAJgIAFgLQAFgLAAgOQAAgNgEgKQgEgKgIgIQgIgIgMgDQgMgFgQAAIgQACIAAg2IgnAAgACwgnIA0AAIAACFIAnAAIAAiFIAzAAIAAglIiOAAgABxBeIAoAAIAAiqIgjAAIhLBpIAAhpIgoAAIAACqIAjAAIBLhpgAhOgnIAACFIAnAAIAAiqIiKAAIAACqIAnAAIAAiFgAlOBWIALAFQAIADAHAAQAJAAAHgDQAHgDAHgFQAFgFAGgIQAEgHAEgKIA6iBIgnAAIgjBSIgwhSIgsAAIBJB5IgBAFQgCAEgEABQgDACgEAAQgGAAgHgEgAoAgnIAyAAIAACFIAoAAIAAiFIAyAAIAAglIiMAAgAr7A4IAAgfIAPAAQAJAAAGADQAFAEABAIQAAAIgHAFQgFAFgLAAQgIAAgFgCgAF9A4IAAgrIAMgBQAMAAAHAFQAEACABAFQACAEAAAGQAAAHgCAEQgCAEgCADQgFADgEABQgFACgGAAgAr7gIIAAgfIALgCQAIAAAGAFQAFAEAAAHQABAJgGAEQgFAEgIAAg");
	this.shape_2.setTransform(102,28.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,204,59.1);


// stage content:
(lib.fonbet_club = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(-23,-16,0.894,0.894);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// btn
	this.instance_1 = new lib.Символ11();
	this.instance_1.parent = this;
	this.instance_1.setTransform(359.1,229.5,1,1,0,0,0,102,29.5);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// 5
	this.instance_2 = new lib.Символ46();
	this.instance_2.parent = this;
	this.instance_2.setTransform(633.5,162,1,1,0,0,0,152.5,150);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// 4
	this.instance_3 = new lib.Символ37();
	this.instance_3.parent = this;
	this.instance_3.setTransform(159.6,149.3,1,1,0,0,0,53.5,87.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// 3
	this.instance_4 = new lib.Символ28();
	this.instance_4.parent = this;
	this.instance_4.setTransform(508,11);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// 2
	this.instance_5 = new lib.Символ14();
	this.instance_5.parent = this;
	this.instance_5.setTransform(413,5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

	// 1
	this.instance_6 = new lib.Символ1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(421.5,139.5,1,1,0,0,0,257.5,139.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1));

	// bg
	this.instance_7 = new lib.Символ35();
	this.instance_7.parent = this;
	this.instance_7.setTransform(365,136,1,1,0,0,0,375,150);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(50,-125.4,1330,627.2);
// library properties:
lib.properties = {
	width: 726,
	height: 270,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg?1510837581683", id:"bg"},
		{src:"images/dacyuk.png?1510837581683", id:"dacyuk"},
		{src:"images/headphone.png?1510837581683", id:"headphone"},
		{src:"images/iphone.png?1510837581683", id:"iphone"},
		{src:"images/kaprizov.png?1510837581683", id:"kaprizov"},
		{src:"images/kokorin.png?1510837581683", id:"kokorin"},
		{src:"images/logo.png?1510837581683", id:"logo"},
		{src:"images/samedov.png?1510837581683", id:"samedov"},
		{src:"images/samsung.png?1510837581683", id:"samsung"},
		{src:"images/seif.png?1510837581683", id:"seif"},
		{src:"images/shved.png?1510837581683", id:"shved"},
		{src:"images/slayd1.jpg?1510837581683", id:"slayd1"},
		{src:"images/slayd2.jpg?1510837581683", id:"slayd2"},
		{src:"images/slayd3.jpg?1510837581683", id:"slayd3"},
		{src:"images/smolov.png?1510837581683", id:"smolov"},
		{src:"images/tv.png?1510837581683", id:"tv"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;